import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';
const {generateCollision}=createRequire(import.meta.url)('../desktop/collision.cjs');
test('collision cancellation cleans partial output and preserves input',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'spark-collision-'));try{const source=path.join(root,'original.ply');await fs.writeFile(source,'original bytes');const job=generateCollision({source,projectRoot:root,executable:process.execPath,cli:'unused'});job.cancel();await assert.rejects(job.promise,/cancelled/);assert.equal(await fs.readFile(source,'utf8'),'original bytes');assert.deepEqual(await fs.readdir(path.join(root,'assets/collisions')),[]);}finally{await fs.rm(root,{recursive:true,force:true});}});
test('collision generation rejects unsafe or invalid resolution',()=>{for(const voxelSize of [NaN,0,-1,Infinity,100])assert.throws(()=>generateCollision({source:'source.ply',projectRoot:'.',voxelSize}),/resolution/);});

test('collision generation preserves the first GPU error and stops the failing process',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'spark-gpu-failure-'));
 try{const source=path.join(root,'original.ply'),cli=path.join(root,'fake-cli.cjs');const original='ply\nformat ascii 1.0\nelement vertex 2\nend_header\n';await fs.writeFile(source,original);await fs.writeFile(cli,"process.stderr.write('WebGPU error: Buffer size exceeds max buffer size limit\\n');setInterval(()=>process.stderr.write('validation: Invalid BindGroup\\n'),50);");const job=generateCollision({source,projectRoot:root,executable:process.execPath,cli});await assert.rejects(job.promise,/WebGPU error: Buffer size exceeds max buffer size limit/);assert.equal(await fs.readFile(source,'utf8'),original);assert.deepEqual(await fs.readdir(path.join(root,'assets/collisions')),[]);const logs=await fs.readdir(path.join(root,'collision-logs'));assert.equal(logs.length,1);assert.match(await fs.readFile(path.join(root,'collision-logs',logs[0]),'utf8'),/WebGPU error/);
 }finally{await fs.rm(root,{recursive:true,force:true});}
});
