import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {createRequire} from 'node:module';
import {blankProject,newScene,validateProject,sceneUrl,renderPage} from '../shared/project.mjs';
const require=createRequire(import.meta.url);const {startServer,rangeFor}=require('../desktop/server.cjs');const {exportTour}=require('../desktop/export.cjs');
function fixture(){const p=blankProject();p.scenes=[newScene('a','Interior','scene.rad'),newScene('b','Exterior','other.rad')];p.startScene='a';return p;}
test('project validation finds broken links, missing walk geometry and unsafe page IDs',()=>{const p=fixture();assert.deepEqual(validateProject(p),[]);p.scenes[0].modes.push('explore');p.scenes[0].hotspots.push({id:'h',label:'Broken',kind:'scene',target:'missing',position:[0,1,0]});const errors=validateProject(p);assert.ok(errors.some(e=>e.includes('Walk')));assert.ok(errors.some(e=>e.includes('broken')));p.pages=[{id:'../../escape',title:'bad',html:'',blocks:[]}];assert.ok(validateProject(p).some(e=>e.includes('pages.0.id')));});
test('hosting changes only splat resolution; overrides and subdirectory paths work',()=>{const s=fixture().scenes[0];assert.equal(sceneUrl(s,{assetBaseUrl:'./'},'https://example.com/tours/one/'),'https://example.com/tours/one/scene.rad');assert.equal(sceneUrl(s,{assetBaseUrl:'https://cdn.example/data/'},'https://example.com/'),'https://cdn.example/data/scene.rad');assert.equal(sceneUrl(s,{assetBaseUrl:'./',sceneUrls:{a:'https://other.example/a.rad'}},'https://example.com/'),'https://other.example/a.rad');});
test('generated pages escape text and use local media relative to page folder',()=>{const html=renderPage({title:'<script>bad</script>',blocks:[{type:'text',text:'<img onerror=bad>',url:''},{type:'image',text:'caption',url:'media/photo.jpg'}]});assert.ok(!html.includes('<script>bad'));assert.ok(html.includes('../media/photo.jpg'));});
test('range parser supports bounded, open and suffix ranges and rejects malformed ranges',()=>{assert.deepEqual(rangeFor('bytes=2-6',10),{start:2,end:6});assert.deepEqual(rangeFor('bytes=7-',10),{start:7,end:9});assert.deepEqual(rangeFor('bytes=-3',10),{start:7,end:9});for(const h of ['bytes=50-60','bytes=4-1','bytes=0-1,4-5','bytes=-0'])assert.throws(()=>rangeFor(h,10));});
test('loopback server handles ranges, HEAD, traversal, verbs and Host containment',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'spark server '));await fs.writeFile(path.join(root,'test.rad'),'0123456789');const {server,url}=await startServer({root});try{let r=await fetch(url+'test.rad',{headers:{Range:'bytes=2-5'}});assert.equal(r.status,206);assert.equal(r.headers.get('content-range'),'bytes 2-5/10');assert.equal(await r.text(),'2345');r=await fetch(url+'test.rad',{method:'HEAD'});assert.equal(r.headers.get('content-length'),'10');assert.equal(await r.text(),'');assert.equal((await fetch(url+'test.rad',{headers:{Range:'bytes=30-'}})).status,416);assert.equal((await fetch(url+'%2e%2e%2fsecret.txt')).status,403);assert.equal((await fetch(url+'test.rad',{method:'POST'})).status,405);const status=await new Promise(resolve=>{http.get(url+'test.rad',{headers:{Host:'attacker.invalid'}},r=>{resolve(r.statusCode);r.resume();});});assert.equal(status,403);}finally{await new Promise(r=>server.close(r));await fs.rm(root,{recursive:true,force:true});}});
test('referenced export round trips data and incomplete portable output is marked',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'spark export '));const projectRoot=path.join(root,'project'),dist=path.join(root,'dist'),out=path.join(root,'out');await fs.mkdir(projectRoot);await fs.mkdir(path.join(dist,'assets'),{recursive:true});await fs.mkdir(path.join(dist,'licenses'));await fs.writeFile(path.join(dist,'index.html'),'<html>fixture</html>');await fs.writeFile(path.join(dist,'assets','app.js'),'local code');const launcher=path.join(root,'launcher.exe');await fs.writeFile(launcher,'launcher fixture');const p=fixture();p.pages=[{id:'story',title:'Story',html:'',blocks:[{type:'text',text:'Hello',url:''}]}];p.scenes[0].hotspots.push({id:'story-bubble',label:'Story',kind:'page',target:'story',position:[0,1,0]});const args={project:p,hosting:{assetBaseUrl:'https://cdn.example/',sceneUrls:{}},projectRoot,sources:{},destination:out,dist,launcher,portable:false,omitSplats:true};try{await exportTour(args);assert.deepEqual(JSON.parse(await fs.readFile(path.join(out,'config','tour.json'),'utf8')),p);assert.ok((await fs.readFile(path.join(out,'pages','story.html'),'utf8')).includes('Hello'));await assert.rejects(fs.access(path.join(out,'EXPORT_INCOMPLETE.txt')));await assert.rejects(exportTour(args),/empty export/);const bad=path.join(root,'bad');await assert.rejects(exportTour({...args,hosting:{assetBaseUrl:'./',sceneUrls:{}},destination:bad,portable:true}),/ENOENT/);assert.ok(await fs.readFile(path.join(bad,'EXPORT_INCOMPLETE.txt'),'utf8'));}finally{await fs.rm(root,{recursive:true,force:true});}});
