import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {ImportQueue}=createRequire(import.meta.url)('../desktop/import-queue.cjs');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function harness(){const tasks=[];const queue=new ImportQueue((input,progress,id)=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});tasks.push({input,id,resolve,reject,progress});return {promise,cancel:()=>reject(Error('cancelled'))};});return {queue,tasks};}
const input=(name)=>({name,kind:'ply',options:{method:'quick',maxSh:2}});
test('imports run serially, accept later batches, retain settings and require acknowledgement',async()=>{const {queue:q,tasks}=harness();const settings=input('first');q.enqueue([settings,input('second')]);settings.options.maxSh=0;assert.equal(tasks.length,1);assert.equal(tasks[0].input.options.maxSh,2);q.enqueue([input('third')]);tasks[0].progress('Working');assert.equal(q.snapshot().jobs[0].progress,'Working');tasks[0].resolve({id:tasks[0].id});await tick();assert.equal(tasks.length,2);tasks[1].resolve({});await tick();tasks[2].resolve({});await tick();assert.equal(q.hasWork(),true);q.action('clear');assert.equal(q.jobs.length,3);for(const job of q.jobs)q.action('ack',job.id);assert.equal(q.hasWork(),false);q.action('clear');assert.equal(q.jobs.length,0);});
test('pause finishes current job, queued cancellations never start, resume preserves order',async()=>{const {queue:q,tasks}=harness();q.enqueue([input('first'),input('cancel'),input('last')]);q.action('pause');q.action('cancel',q.jobs[1].id);tasks[0].resolve({});await tick();assert.equal(tasks.length,1);q.action('resume');assert.equal(tasks[1].input.name,'last');tasks[1].resolve({});await tick();});
test('failure and active cancellation allow later jobs, retry is explicit',async()=>{const {queue:q,tasks}=harness();q.enqueue([input('bad'),input('cancel'),input('last')]);tasks[0].reject(Error('bad file'));await tick();assert.equal(q.jobs[0].error,'bad file');q.action('cancel',q.jobs[1].id);assert.equal(q.hasWork(),true);await tick();assert.equal(tasks[2].input.name,'last');tasks[2].resolve({});await tick();q.action('retry',q.jobs[0].id);assert.equal(tasks.length,4);tasks[3].resolve({});await tick();assert.equal(q.jobs[0].state,'completed');});
test('cancel all stops the active worker and pending jobs; reset restores automatic processing',async()=>{const {queue:q,tasks}=harness();q.enqueue([input('first'),input('second')]);q.cancelAll();assert.throws(()=>q.action('reset'),/Finish/);await tick();assert.equal(tasks.length,1);assert.equal(q.hasWork(),false);q.action('reset');assert.equal(q.paused,false);q.enqueue([input('new')]);assert.equal(tasks.length,2);tasks[1].resolve({});await tick();});
