import {characterMovement} from '../shared/walking.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import RAPIER from '@dimforge/rapier3d-compat';
test('Rapier walking capsule grounds, blocks walls, and climbs a low step',async()=>{await RAPIER.init();const world=new RAPIER.World({x:0,y:-9.81,z:0});try{world.createCollider(RAPIER.ColliderDesc.cuboid(20,.1,20).setTranslation(0,-.1,0));world.createCollider(RAPIER.ColliderDesc.cuboid(.1,2,4).setTranslation(3,2,0));world.createCollider(RAPIER.ColliderDesc.cuboid(.4,.1,1).setTranslation(1,.1,0),world.createRigidBody(RAPIER.RigidBodyDesc.fixed()));const body=world.createRigidBody(RAPIER.RigidBodyDesc.kinematicPositionBased().setTranslation(0,.87,0));const capsule=world.createCollider(RAPIER.ColliderDesc.capsule(.6,.25),body);const controller=world.createCharacterController(.015);controller.enableAutostep(.5,.2,false);controller.enableSnapToGround(.3);world.step();let highest=0;for(let i=0;i<240;i++){const m=characterMovement(world,controller,capsule,body,{x:1/60,y:-.02,z:0}),p=body.translation();body.setNextKinematicTranslation({x:p.x+m.x,y:p.y+m.y,z:p.z+m.z});world.step();highest=Math.max(highest,body.translation().y);}assert.ok(body.translation().x<2.7,'wall stops movement');assert.ok(body.translation().x>2.4,'capsule reaches wall: '+JSON.stringify({position:body.translation(),highest}));assert.ok(highest>1,'capsule steps up');assert.ok(body.translation().y>.8,'floor supports capsule');}finally{world.free();}});

import {flyMovement} from '../shared/flying.mjs';
test('drone sweeps stop at floors, ceilings and walls while preserving sliding and vertical flight',async()=>{await RAPIER.init();const world=new RAPIER.World({x:0,y:0,z:0});try{world.createCollider(RAPIER.ColliderDesc.cuboid(10,.1,10).setTranslation(0,-.1,0));world.createCollider(RAPIER.ColliderDesc.cuboid(.1,3,10).setTranslation(2,3,0));world.createCollider(RAPIER.ColliderDesc.cuboid(10,.1,10).setTranslation(0,4.1,0));world.step();const floor=flyMovement(world,{x:0,y:1,z:0},{x:0,y:-10,z:0});assert.ok(1+floor.y>.2&&1+floor.y<.24,'fast descent cannot tunnel through floor');const wall=flyMovement(world,{x:0,y:1,z:0},{x:10,y:1,z:2});assert.ok(wall.x<1.7&&wall.x>1.6);assert.ok(wall.z>1.95&&wall.y>.95,'slides along wall in three dimensions');const ceiling=flyMovement(world,{x:0,y:1,z:0},{x:0,y:10,z:0});assert.ok(1+ceiling.y<3.8&&1+ceiling.y>3.75);const escape=flyMovement(world,{x:1.8,y:1,z:0},{x:-1,y:0,z:0});assert.ok(escape.x<-.99,'camera can move out of initial penetration');const deeper=flyMovement(world,{x:1.8,y:1,z:0},{x:.1,y:0,z:0});assert.ok(deeper.x<.01,'camera cannot move further into wall');const clear=flyMovement(world,{x:0,y:1,z:0},{x:-.1,y:.1,z:.1});assert.deepEqual(clear,{x:-.1,y:.1,z:.1});}finally{world.free();}});

import {nearbyWalkingFeet} from '../shared/walking.mjs';import {nearbyFlyPosition} from '../shared/flying.mjs';
test('mode placement preserves valid positions, finds nearby clearance and rejects missing floors',async()=>{await RAPIER.init();const world=new RAPIER.World({x:0,y:-9.81,z:0});try{world.createCollider(RAPIER.ColliderDesc.cuboid(10,.1,10).setTranslation(0,-.1,0));world.createCollider(RAPIER.ColliderDesc.cuboid(.2,2,.2).setTranslation(1,2,1));world.step();const feet=nearbyWalkingFeet(world,{x:3,y:1.7,z:2},1.7);assert.ok(Math.abs(feet.x-3)<.001&&Math.abs(feet.z-2)<.001&&Math.abs(feet.y)<.001);const near=nearbyWalkingFeet(world,{x:1,y:1.7,z:1},1.7);assert.ok(near&&Math.hypot(near.x-1,near.z-1)<=1,'escape a viewpoint inside a wall');assert.equal(nearbyWalkingFeet(world,{x:30,y:1.7,z:30},1.7),null);const fly=nearbyFlyPosition(world,{x:3,y:3,z:2});assert.deepEqual(fly,{x:3,y:3,z:2});const escape=nearbyFlyPosition(world,{x:1,y:1,z:1});assert.ok(escape&&Math.hypot(escape.x-1,escape.y-1,escape.z-1)<=1);assert.equal(world.intersectionWithShape(escape,{x:0,y:0,z:0,w:1},new RAPIER.Ball(.2)),null);}finally{world.free();}});

test('walking-mode placement handles slope clearance and rejects low ceilings',async()=>{await RAPIER.init();const slope=new RAPIER.World({x:0,y:-9.81,z:0}),low=new RAPIER.World({x:0,y:-9.81,z:0});try{const angle=Math.PI/8;slope.createCollider(RAPIER.ColliderDesc.cuboid(5,.1,5).setTranslation(0,-.1,0).setRotation({x:0,y:0,z:Math.sin(angle/2),w:Math.cos(angle/2)}));slope.step();const feet=nearbyWalkingFeet(slope,{x:0,y:1.7,z:0},1.7);assert.ok(feet);assert.equal(slope.intersectionWithShape({x:feet.x,y:feet.y+.87,z:feet.z},{x:0,y:0,z:0,w:1},new RAPIER.Capsule(.6,.25)),null);low.createCollider(RAPIER.ColliderDesc.cuboid(10,.1,10).setTranslation(0,-.1,0));low.createCollider(RAPIER.ColliderDesc.cuboid(10,.1,10).setTranslation(0,1.4,0));low.step();assert.equal(nearbyWalkingFeet(low,{x:0,y:1,z:0},1.7),null);}finally{slope.free();low.free();}});
