import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {EventEmitter} from 'node:events';import {createRequire} from 'node:module';
import {createRecovery,parseRecovery} from '../shared/recovery.mjs';import {blankProject,newScene,ProjectSchema,HostingSchema,sceneUrl} from '../shared/project.mjs';
const {startServer}=createRequire(import.meta.url)('../desktop/server.cjs'),{attachClose}=createRequire(import.meta.url)('../desktop/close.cjs');
function project(){const p=blankProject();p.scenes=[newScene('north','North','assets/converted/new/source-lod.rad')];p.startScene='north';return p;}

test('recovery retains unsaved PLY source and relative hosting override together',()=>{const p=project(),savedHosting={assetBaseUrl:'https://cdn.example/',sceneUrls:{north:'https://cdn.example/old.rad'}},updatedHosting={...savedHosting,sceneUrls:{north:p.scenes[0].source}},before=structuredClone({p,updatedHosting});const file=createRecovery(p,updatedHosting),recovered=parseRecovery(JSON.parse(JSON.stringify(file)),savedHosting);assert.equal(file.format,'spark-tour-recovery');assert.equal(file.version,1);assert.deepEqual(recovered,{project:p,hosting:updatedHosting});assert.equal(sceneUrl(recovered.project.scenes[0],recovered.hosting,'https://tour.example/project/'),'https://tour.example/project/assets/converted/new/source-lod.rad');assert.ok(!JSON.stringify(file).includes('127.0.0.1'));assert.deepEqual({p,updatedHosting},before);});

test('legacy bare-project autosaves remain compatible with saved hosting and malformed envelopes are rejected',()=>{const p=project(),hosting={assetBaseUrl:'https://cdn.example/',sceneUrls:{}};assert.deepEqual(parseRecovery(p,hosting),{project:p,hosting});assert.deepEqual(parseRecovery(p),{project:p,hosting:{assetBaseUrl:'./',sceneUrls:{}}});assert.equal(parseRecovery(undefined,hosting),undefined);assert.throws(()=>parseRecovery({...createRecovery(p,hosting),version:2}));assert.throws(()=>parseRecovery({...createRecovery(p,hosting),hosting:{assetBaseUrl:'javascript:bad',sceneUrls:{}}}));});

test('loopback server keeps recovery/source mappings private while public JSON and asset ranges work',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'spark recovery privacy '));let server;try{await fs.mkdir(path.join(root,'project'),{recursive:true});for(const name of ['autosave.json','autosave.json.tmp','.sources.json','.sources.json.tmp'])await fs.writeFile(path.join(root,'project',name),'private');await fs.writeFile(path.join(root,'project','public.json'),'public');await fs.writeFile(path.join(root,'project','scan.rad'),'0123456789');const running=await startServer({root});server=running.server;for(const name of ['autosave.json','autosave.json.tmp','.sources.json','.sources.json.tmp','%61utosave.json','AUTOSAVE.JSON','autosave.json.','autosave.json%20','autosave.json..%20','autosave.json.tmp.','.sources.json.','.sources.json%20','.sources.json.tmp%20.'])for(const method of ['GET','HEAD'])assert.equal((await fetch(running.url+'project/'+name,{method})).status,403,name);assert.equal(await(await fetch(running.url+'project/public.json')).text(),'public');const range=await fetch(running.url+'project/scan.rad',{headers:{Range:'bytes=2-5'}});assert.equal(range.status,206);assert.equal(await range.text(),'2345');}finally{if(server)await new Promise(resolve=>server.close(resolve));await fs.rm(root,{recursive:true,force:true});}});

test('save-and-close saves both configurations and waits for pending recovery cleanup',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'spark recovery close '));try{const p=project(),hosting={assetBaseUrl:'https://cdn.example/',sceneUrls:{north:p.scenes[0].source}},win=new EventEmitter();win.webContents=new EventEmitter();win.webContents.executeJavaScript=async()=>({dirty:true,project:p,hosting});let done;const closed=new Promise(resolve=>done=resolve);win.destroy=()=>done();let cleanupCalled=false;const pendingWrite=new Promise(resolve=>setImmediate(async()=>{await fs.writeFile(path.join(root,'autosave.json'),JSON.stringify(createRecovery(p,hosting)));resolve();}));attachClose({win,dialog:{showMessageBox:async()=>({response:0})},model:{ProjectSchema,HostingSchema},getRoot:()=>root,getSources:()=>({}),isBusy:()=>false,cancelJob:()=>{},clearRecovery:async dir=>{cleanupCalled=true;assert.equal(dir,root);await pendingWrite;await fs.unlink(path.join(dir,'autosave.json'));}});win.emit('close',{preventDefault(){}});await closed;assert.equal(cleanupCalled,true);assert.deepEqual(JSON.parse(await fs.readFile(path.join(root,'config/tour.json'),'utf8')),p);assert.deepEqual(JSON.parse(await fs.readFile(path.join(root,'config/hosting.json'),'utf8')),hosting);await assert.rejects(fs.access(path.join(root,'autosave.json')));}finally{await fs.rm(root,{recursive:true,force:true});}});
