import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import http from 'node:http';import {createRequire} from 'node:module';
import {RichTextSchema,plainTextDocument,richTextForBlock,richTextPlainText,richTextToBlocks,richTextReferences,mapRichTextReferences,renderRichText,safeContentReference} from '../shared/rich-text.mjs';
import {blankProject,newScene,ProjectSchema,allReferences,renderPage} from '../shared/project.mjs';
const {exportTour}=createRequire(import.meta.url)('../desktop/export.cjs');
const text=(value,marks)=>({type:'text',text:value,...marks?{marks}:{}});
function rich(){return {version:1,doc:{type:'doc',content:[{type:'heading',attrs:{level:2},content:[text('The history')]},{type:'paragraph',content:[text('A '),text('remarkable',{length:0})]},{type:'bulletList',content:[{type:'listItem',content:[{type:'paragraph',content:[text('First place')]}]}]},{type:'blockquote',content:[{type:'paragraph',content:[text('Remember this')]}]},{type:'paragraph',content:[text('Read more',[{type:'link',attrs:{href:'media/history.pdf',target:'_blank'}}])]},{type:'image',attrs:{src:'media/photo.jpg',alt:'Historic photo',onerror:'alert(1)'}}]}};}
function project(value){const p=blankProject();p.scenes=[newScene('north','North','https://cdn.example/main.rad')];p.startScene='north';p.scenes[0].hotspots=[{id:'story',label:'Story',kind:'page',target:'story',position:[0,1,0],createdAt:100}];p.pages=[{id:'story',title:'Story',html:'',blocks:[{type:'text',text:'Legacy fallback',url:'',richText:value}]}];return p;}

test('plain text is preserved on migration, including repeated newlines and markup characters',()=>{const plain='A <place> & a story\n\nThird line\n';const migrated=RichTextSchema.parse(richTextForBlock({text:plain}));assert.equal(richTextPlainText(migrated),plain);assert.match(renderRichText(migrated),/A &lt;place&gt; &amp; a story/);assert.deepEqual(RichTextSchema.parse(JSON.parse(JSON.stringify(migrated))),migrated);});

test('paragraph and heading alignment persists and renders safely in popups and pages',()=>{for(const alignment of ['left','center','right','justify']){const value=plainTextDocument('A history\nSecond line');value.doc.content[0].attrs={textAlign:alignment};value.doc.content.push({type:'heading',attrs:{level:2,textAlign:alignment},content:[text('A title')]});const p=ProjectSchema.parse(project(value)),saved=p.pages[0].blocks[0].richText;assert.deepEqual(ProjectSchema.parse(JSON.parse(JSON.stringify(p))),p);assert.equal(saved.doc.content[0].attrs.textAlign,alignment);assert.equal(saved.doc.content[1].attrs.level,2);assert.equal(saved.doc.content[1].attrs.textAlign,alignment);assert.ok(renderRichText(saved).includes('text-align:'+alignment));assert.ok(renderPage(p.pages[0]).includes('text-align:'+alignment));assert.equal(richTextPlainText(saved),'A history\nSecond line\nA title');}const unsafe=plainTextDocument('Unsafe');unsafe.doc.content[0].attrs={textAlign:'left;color:red'};assert.equal(RichTextSchema.safeParse(unsafe).success,false);unsafe.doc.content[0].attrs={textAlign:null};assert.equal(RichTextSchema.parse(unsafe).doc.content[0].attrs,undefined);});

test('formatted documents round trip, sanitize attributes and render shared browser/page markup',()=>{const value=rich();value.doc.content[1].content[1].marks=[{type:'bold'},{type:'italic'},{type:'underline'}];const p=ProjectSchema.parse(project(value)),saved=p.pages[0].blocks[0].richText;assert.deepEqual(ProjectSchema.parse(JSON.parse(JSON.stringify(p))),p);const html=renderRichText(saved,'https://local.example/tour/');assert.match(html,/<h2>The history<\/h2>/);assert.match(html,/<u><em><strong>remarkable<\/strong><\/em><\/u>/);assert.match(html,/<ul><li><p>First place<\/p><\/li><\/ul>/);assert.match(html,/href="https:\/\/local.example\/tour\/media\/history.pdf"/);assert.match(html,/src="https:\/\/local.example\/tour\/media\/photo.jpg"/);assert.ok(!html.includes('onerror'));assert.match(renderPage(p.pages[0]),/src="..\/media\/photo.jpg"/);assert.match(renderPage(p.pages[0]),/href="..\/media\/history.pdf"/);});

test('rich text rejects unsafe URLs, foreign nodes, excessive nesting and unsupported versions',()=>{for(const ref of ['javascript:alert(1)','data:text/html,bad','//evil.example/a','file:///C:/secret','../escape','%2e%2e/escape','/root','https://example.com/\nsecret'])assert.equal(safeContentReference(ref),false,ref);for(const ref of ['https://example.com/a b.jpg','media/a b.jpg','#history','media/photo.jpg?x=1#section'])assert.equal(safeContentReference(ref),true,ref);for(const bad of ['javascript:alert(1)','data:image/png;base64,AA','../escape']){const value=plainTextDocument('Link');value.doc.content[0].content[0].marks=[{type:'link',attrs:{href:bad}}];assert.equal(RichTextSchema.safeParse(value).success,false);assert.equal(renderRichText(value),'');}assert.equal(RichTextSchema.safeParse({version:2,doc:{type:'doc'}}).success,false);assert.equal(RichTextSchema.safeParse({version:1,doc:{type:'doc',content:[{type:'iframe'}]}}).success,false);let nested={type:'paragraph',content:[]};for(let i=0;i<30;i++)nested={type:'blockquote',content:[nested]};assert.equal(RichTextSchema.safeParse({version:1,doc:{type:'doc',content:[nested]}}).success,false);});

test('XR output retains lists, distinct actionable links and image sources',()=>{const value=rich();value.doc.content[1].content[1].marks=[{type:'bold'}];const blocks=richTextToBlocks(RichTextSchema.parse(value));assert.ok(blocks.some(b=>b.type==='text'&&b.text==='• First place'));assert.ok(blocks.some(b=>b.type==='link'&&b.text==='Read more'&&b.url==='media/history.pdf'));assert.ok(blocks.some(b=>b.type==='image'&&b.text==='Historic photo'&&b.url==='media/photo.jpg'));});

test('asset traversal follows nested images and links, rewrite leaves input untouched',async()=>{const value=rich();value.doc.content[1].content[1].marks=[];const clean=RichTextSchema.parse(value),before=structuredClone(clean);assert.deepEqual(richTextReferences(clean),[{ref:'media/history.pdf',kind:'link'},{ref:'media/photo.jpg',kind:'image'}]);const mapped=await mapRichTextReferences(clean,async(ref,kind)=>kind==='image'?'imports/copy.jpg':ref);assert.deepEqual(clean,before);assert.ok(richTextReferences(mapped).some(r=>r.ref==='imports/copy.jpg'));const p=ProjectSchema.parse(project(clean));assert.ok(allReferences(p).includes('media/photo.jpg'));assert.ok(allReferences(p).includes('media/history.pdf'));p.pages[0].html='custom/index.html';assert.ok(!allReferences(p).includes('media/photo.jpg'));});

test('portable export downloads nested remote images and copies local linked assets without altering authors data',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'spark rich export ')),server=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'image/jpeg'});res.end('remote photo');});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const projectRoot=path.join(root,'project'),dist=path.join(root,'dist'),launcher=path.join(root,'launcher.exe'),destination=path.join(root,'out');await fs.mkdir(path.join(projectRoot,'media'),{recursive:true});await fs.mkdir(path.join(dist,'assets'),{recursive:true});await fs.mkdir(path.join(dist,'licenses'));await fs.writeFile(path.join(dist,'index.html'),'fixture');await fs.writeFile(launcher,'fixture');await fs.writeFile(path.join(projectRoot,'media/history.pdf'),'history');const value=rich();value.doc.content[1].content[1].marks=[];value.doc.content.at(-1).attrs.src=`http://127.0.0.1:${server.address().port}/photo.jpg`;const p=project(value);p.scenes[0].source='main.rad';const {radFixture}=await import('./fixtures.mjs');await fs.writeFile(path.join(projectRoot,'main.rad'),radFixture().rad);const before=structuredClone(p);await exportTour({project:p,hosting:{assetBaseUrl:'./',sceneUrls:{}},projectRoot,sources:{},destination,dist,launcher,portable:true,omitSplats:false});const saved=JSON.parse(await fs.readFile(path.join(destination,'config/tour.json'),'utf8'));const refs=richTextReferences(saved.pages[0].blocks[0].richText),image=refs.find(r=>r.kind==='image').ref;assert.equal(await fs.readFile(path.join(destination,image),'utf8'),'remote photo');assert.equal(await fs.readFile(path.join(destination,'media/history.pdf'),'utf8'),'history');const html=await fs.readFile(path.join(destination,'pages/story.html'),'utf8');assert.ok(html.includes('../'+image));assert.ok(!html.includes('127.0.0.1'));assert.deepEqual(p,before);assert.deepEqual(ProjectSchema.parse(saved),saved);}finally{await new Promise(resolve=>server.close(resolve));await fs.rm(root,{recursive:true,force:true});}});
