import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {existsSync} from 'node:fs';import {createRequire} from 'node:module';
import {blankProject,newScene,ProjectSchema,sceneUrl} from '../shared/project.mjs';import {applySceneImport,setSceneSource} from '../shared/authoring.mjs';import {plyFixture,radFixture} from './fixtures.mjs';
const {ImportQueue}=createRequire(import.meta.url)('../desktop/import-queue.cjs'),{convertPly}=createRequire(import.meta.url)('../desktop/converter.cjs');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(){const p=blankProject(),s=newScene('north','North','assets/converted/old/source-lod.rad');p.scenes=[s,newScene('south','South','south.rad')];p.startScene='north';s.transform={position:[2,3,4],rotation:[.2,.1,.3],scale:1.5};s.collider='collision.glb';s.colliderTransform={position:[1,0,1],rotation:[0,.1,0],scale:.8};s.walkHeight=1.9;s.modes=['jumps','fly','explore'];s.background={type:'solid',color:'#223344'};s.audio={source:'scene.mp3',loop:true,volume:.7};s.viewpoints.push({id:'extra',name:'Side view',position:[2,2,2],rotation:[0,1,0],description:'Remember this',listed:false,audio:{source:'view.mp3',loop:false,volume:.9}});s.hotspots=[{id:'info',label:'History',position:[1,2,3],kind:'page',target:'story',size:1,createdAt:123},{id:'view',label:'',position:[2,3,4],kind:'viewpoint',target:'extra'}];p.scenes[1].hotspots=[{id:'north-link',label:'',position:[1,1,1],kind:'scene',target:'north',viewpoint:'extra'}];p.pages=[{id:'story',title:'History',html:'',blocks:[{type:'image',text:'Historical photo',url:'photo.jpg'}]}];return p;}
function replacement(p,state='completed'){return {id:'import-job',name:'North',kind:'ply',replaceSceneId:'north',expectedSource:p.scenes[0].source,state,result:newScene('import-job','scan name','assets/converted/new/source-lod.rad')};}

test('PLY re-import changes only the source while preserving annotations and edits made during conversion',()=>{const p=fixture(),job=replacement(p);p.scenes[0].hotspots[0].label='Edited while converting';p.pages[0].blocks[0].text='New caption';const before=structuredClone(p);assert.deepEqual(applySceneImport(p,job),{status:'replaced',sceneId:'north',source:job.result.source});before.scenes[0].source=job.result.source;assert.deepEqual(p,before);assert.equal(p.scenes.length,2);assert.equal(p.scenes[1].hotspots[0].target,'north');assert.deepEqual(ProjectSchema.parse(p),p);assert.deepEqual(applySceneImport(p,job),{status:'already'});});

test('failed, cancelled and unfinished replacements never change a scene; changed sources and deleted targets are respected',()=>{for(const state of ['queued','running','failed','cancelled']){const p=fixture(),before=structuredClone(p);assert.equal(applySceneImport(p,replacement(p,state)).status,'ignored');assert.deepEqual(p,before);}let p=fixture(),job=replacement(p);p.scenes[0].source='another.rad';const before=structuredClone(p);assert.equal(applySceneImport(p,job).status,'discarded');assert.deepEqual(p,before);p=fixture();job=replacement(p);p.scenes=p.scenes.filter(s=>s.id!=='north');assert.equal(applySceneImport(p,job).status,'discarded');assert.equal(p.scenes.length,1);});

test('replacement metadata survives queue snapshots, cancel and failure with no premature application',async()=>{const p=fixture(),old=structuredClone(p),tasks=[];const q=new ImportQueue(input=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});tasks.push({resolve,reject,input});return {promise,cancel:()=>reject(Error('cancelled'))};},state=>{for(const job of state.jobs)applySceneImport(p,job);});const input={kind:'ply',name:'North',replaceSceneId:'north',expectedSource:p.scenes[0].source,options:{method:'quality',maxSh:3}};q.enqueue([input]);assert.equal(q.snapshot().jobs[0].replaceSceneId,'north');assert.equal(q.snapshot().jobs[0].expectedSource,old.scenes[0].source);input.replaceSceneId='south';q.action('cancel',q.jobs[0].id);await tick();assert.deepEqual(p,old);q.action('retry',q.jobs[0].id);tasks[1].reject(Error('bad PLY'));await tick();assert.deepEqual(p,old);q.action('retry',q.jobs[0].id);tasks[2].resolve(newScene('job','Ignored import name','assets/converted/new/source-lod.rad'));await tick();assert.equal(p.scenes[0].source,'assets/converted/new/source-lod.rad');assert.deepEqual(p.scenes[0].hotspots,old.scenes[0].hotspots);assert.equal(p.scenes.length,2);});

test('discarded replacement is acknowledged without an error and keeps an explicit queue outcome',async()=>{const q=new ImportQueue(()=>({promise:Promise.resolve(newScene('north','North','replacement.rad')),cancel:()=>{}}));q.enqueue([{name:'North',kind:'ply',replaceSceneId:'north',expectedSource:'old.rad'}]);await tick();q.action('discard',q.jobs[0].id);const job=q.snapshot().jobs[0];assert.equal(job.state,'completed');assert.equal(job.acknowledged,true);assert.match(job.progress,/not applied/);assert.equal(job.error,undefined);assert.equal(q.hasWork(),false);});

test('explicit source edits update existing overrides without changing annotations or unrelated delivery settings',()=>{const p=fixture(),before=structuredClone(p),h={assetBaseUrl:'https://cdn.example/scans/',sceneUrls:{north:p.scenes[0].source,south:'https://other.example/south.rad'}};setSceneSource(p,h,'north','imports/relinked/replacement.rad');before.scenes[0].source='imports/relinked/replacement.rad';assert.deepEqual(p,before);assert.deepEqual(h,{assetBaseUrl:'https://cdn.example/scans/',sceneUrls:{north:'imports/relinked/replacement.rad',south:'https://other.example/south.rad'}});assert.equal(sceneUrl(p.scenes[0],h,'https://tour.example/project/'),'https://tour.example/project/imports/relinked/replacement.rad');setSceneSource(p,h,'north','https://fresh.example/new.rad');assert.equal(h.sceneUrls.north,'https://fresh.example/new.rad');assert.equal(sceneUrl(p.scenes[0],h,'https://tour.example/project/'),'https://fresh.example/new.rad');});

test('native RAD relinks remain local with CDN or subfolder bases; manual sources retain configured base semantics',()=>{for(const base of ['https://cdn.example/scans/','splats/']){const p=fixture(),h={assetBaseUrl:base,sceneUrls:{}};setSceneSource(p,h,'north','imports/relinked/replacement.rad',true);assert.equal(h.sceneUrls.north,p.scenes[0].source);assert.equal(sceneUrl(p.scenes[0],h,'https://tour.example/project/'),'https://tour.example/project/imports/relinked/replacement.rad');}const p=fixture(),h={assetBaseUrl:'https://cdn.example/scans/',sceneUrls:{south:'https://other.example/south.rad'}};setSceneSource(p,h,'north','new.rad');assert.equal(h.sceneUrls.north,undefined);assert.equal(sceneUrl(p.scenes[0],h,'https://tour.example/project/'),'https://cdn.example/scans/new.rad');const local={assetBaseUrl:'./',sceneUrls:{}};setSceneSource(p,local,'north','imports/relinked/replacement.rad',true);assert.deepEqual(local,{assetBaseUrl:'./',sceneUrls:{}});});

test('real replacement conversion stages distinct files, preserves old RAD and source PLY through failure and cancellation',{skip:!existsSync(path.resolve('converter/build-lod.exe'))},async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'spark reimport '));try{const executable=path.resolve('converter/build-lod.exe'),p=fixture(),oldPath=path.join(root,p.scenes[0].source),oldBytes=radFixture().rad,source=path.join(root,'updated scan.ply');await fs.mkdir(path.dirname(oldPath),{recursive:true});await fs.writeFile(oldPath,oldBytes);await fs.writeFile(source,plyFixture());const before=structuredClone(p),ref=await convertPly({source,projectRoot:root,executable,method:'quick',maxSh:3}).promise;assert.notEqual(ref,p.scenes[0].source);assert.deepEqual(await fs.readFile(oldPath),oldBytes);assert.deepEqual(p,before);const job=replacement(p);job.result.source=ref;assert.equal(applySceneImport(p,job).status,'replaced');const committed=structuredClone(p);await fs.writeFile(source,'not a PLY');await assert.rejects(convertPly({source,projectRoot:root,executable}).promise,/failed/);assert.deepEqual(p,committed);assert.deepEqual(await fs.readFile(oldPath),oldBytes);await fs.writeFile(source,plyFixture());const cancelled=convertPly({source,projectRoot:root,executable});cancelled.cancel();await assert.rejects(cancelled.promise,/cancelled/);assert.deepEqual(p,committed);assert.deepEqual(await fs.readFile(oldPath),oldBytes);assert.deepEqual(await fs.readFile(source),plyFixture());assert.ok(!(await fs.readdir(root)).some(name=>name.startsWith('.conversion-')));}finally{await fs.rm(root,{recursive:true,force:true});}});
