const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),https=require('node:https'),crypto=require('node:crypto');
const selfsigned=require('selfsigned'),QR=require('qrcode');
const {fileResponse}=require('../desktop/server.cjs');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function networkAddresses(){return Object.entries(os.networkInterfaces()).flatMap(([name,entries])=>(entries||[]).filter(e=>e.family==='IPv4'&&!e.internal&&/^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(e.address)).map(e=>({name,address:e.address})));}
async function certificate(root,host,cacheRoot=path.join(process.env.LOCALAPPDATA||os.tmpdir(),'Spark Tour Launcher')){
 const dir=path.join(cacheRoot,crypto.createHash('sha256').update(path.resolve(root)).digest('hex').slice(0,24));await fs.mkdir(dir,{recursive:true});const file=path.join(dir,'tls.json');
 try{const saved=JSON.parse(await fs.readFile(file,'utf8'));const cert=new crypto.X509Certificate(saved.cert);if(saved.host===host&&Date.parse(cert.validTo)>Date.now()+86400000)return saved;}catch{}
 const pem=await selfsigned.generate([{name:'commonName',value:'Spark Tour local sharing'}],{keySize:2048,algorithm:'sha256',notBeforeDate:new Date(Date.now()-300000),notAfterDate:new Date(Date.now()+365*86400000),extensions:[{name:'basicConstraints',cA:false},{name:'keyUsage',digitalSignature:true,keyEncipherment:true},{name:'extKeyUsage',serverAuth:true},{name:'subjectAltName',altNames:[{type:7,ip:host}]}]});
 const result={host,key:pem.private,cert:pem.cert};await fs.writeFile(file,JSON.stringify(result),{mode:0o600});return result;
}
async function startSharing({root,host,cacheRoot,port=8443}){
 const tls=await certificate(root,host,cacheRoot);const server=https.createServer(tls,async(req,res)=>{
  if(req.headers.host!==host+':'+server.address().port){res.writeHead(403).end();return;}
  if(!['GET','HEAD'].includes(req.method)){res.writeHead(405).end();return;}
  let name;try{name=decodeURIComponent(new URL(req.url,'https://'+host).pathname).slice(1)||'index.html';}catch{res.writeHead(400).end();return;}
  // Share tour resources, never launcher controls, private keys or authoring recovery data.
  if(name.split('/').some(p=>p.startsWith('.')||p.startsWith('__'))||['autosave.json','package.json','package-lock.json'].includes(name)||!/\.(html?|css|m?js|json|wasm|radc?|glb|gltf|bin|png|jpe?g|webp|avif|gif|svg|mp4|webm|mp3|m4a|aac|flac|ogg|wav|woff2?|ttf|pdf)$/i.test(name)){res.writeHead(404).end();return;}
  res.setHeader('Permissions-Policy','xr-spatial-tracking=(self)');await fileResponse(req,res,root,name);
 });
 await new Promise((resolve,reject)=>{const listen=p=>{server.once('error',error=>{if(error.code==='EADDRINUSE'&&p!==0)listen(0);else reject(error);});server.listen(p,host,()=>{server.removeAllListeners('error');resolve();});};listen(port);});
 const url='https://'+host+':'+server.address().port+'/';return {server,url,qr:await QR.toString(url,{type:'svg',margin:2,width:220,color:{dark:'#29495aff',light:'#ffffffff'}})};
}
function createSharingControl(root){let shared,starting=false,error='';return async({name,req,res,token})=>{
 if(!['__launcher','__share','__unshare'].includes(name))return false;
 if(name!=='__launcher'){
  if(req.method!=='POST'){res.writeHead(405).end();return true;}let body='';for await(const chunk of req){body+=chunk;if(body.length>2048){res.writeHead(413).end();return true;}}const data=new URLSearchParams(body);if(data.get('token')!==token){res.writeHead(403).end();return true;}
  try{if(name==='__unshare'){shared?.server.closeAllConnections();shared?.server.close();shared=undefined;}else if(!shared&&!starting){const host=data.get('address');if(!networkAddresses().some(n=>n.address===host))throw Error('Choose a current Wi-Fi or Ethernet address.');starting=true;try{shared=await startSharing({root,host});error='';}finally{starting=false;}}}catch(e){error=e.message;}res.writeHead(303,{Location:'/__launcher'}).end();return true;
 }
 if(req.method!=='GET'){res.writeHead(405).end();return true;}const addresses=networkAddresses();
 res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Frame-Options':'DENY'}).end(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Share your tour</title><style>body{font:15px/1.6 system-ui;color:#334d5e;background:linear-gradient(135deg,#e6eff4,#f6f4ef);max-width:740px;margin:50px auto;padding:20px}section{background:#ffffffb8;border:1px solid white;border-radius:24px;padding:30px;margin:20px 0;box-shadow:0 14px 70px #3e596415}h1{font-weight:450;font-size:34px;letter-spacing:-1px}h2{font-size:19px;font-weight:550}small,p{color:#6a8190}button,a.button,select{font:inherit;border:1px solid #c7d8e1;border-radius:12px;padding:10px 17px;background:#edf5f9;color:#355c75;text-decoration:none;cursor:pointer}select{max-width:100%;margin:0 10px 12px 0}a{color:#487b97}.qr{display:flex;gap:24px;flex-wrap:wrap;align-items:center}.qr svg{width:190px;height:190px;border-radius:18px}.url{overflow-wrap:anywhere;font-size:18px}.note{font-size:13px}.error{color:#a05c46}</style><small>SPARK TOUR · LOCAL LAUNCHER</small><h1>Your place. Their perspective.</h1><p>Keep this window running while people explore.</p><section><h2>On this computer</h2><a class="button" href="/" target="_blank">Open tour ↗</a></section><section><h2>Share on your local network</h2>${shared?`<div class="qr">${shared.qr}<div><p>Scan on a phone, or enter this address<br>in the Quest browser.</p><a class="url" href="${esc(shared.url)}" target="_blank">${esc(shared.url)}</a></div></div><p class="note">Use the same Wi-Fi or Ethernet network. On first use, this local HTTPS certificate causes a browser warning. Check that the address matches the one above, then continue to your tour. In Quest Browser, select Enter VR after the scene loads.</p><p class="note">If it cannot connect, allow this launcher through Windows Firewall on your private network. Guest Wi-Fi or access-point isolation can block devices from reaching each other.</p><form method="post" action="/__unshare"><input type="hidden" name="token" value="${token}"><button>Stop sharing</button></form>`:`<p>Open the tour on a standalone Quest, phone or another computer. Sharing is read-only and stays on the selected network.</p>${addresses.length?`<form method="post" action="/__share"><input type="hidden" name="token" value="${token}"><select aria-label="Network" name="address">${addresses.map(n=>`<option value="${esc(n.address)}">${esc(n.name)} · ${esc(n.address)}</option>`).join('')}</select><button>${starting?'Starting…':'Share on this network'}</button></form>`:'<p>Connect this computer to Wi-Fi or Ethernet, then reload this page.</p>'}`}<p class="error">${esc(error)}</p></section><form method="post" action="/__shutdown"><input type="hidden" name="token" value="${token}"><button>Stop tour server</button></form></html>`);return true;
 };}
module.exports={networkAddresses,certificate,startSharing,createSharingControl};
