import {z} from 'zod';
const number=(min,max,value)=>z.number().finite().min(min).max(max).default(value);
export const PerformanceSettingsSchema=z.object({
 pagedExtSplats:z.boolean().default(false),
 pixelRatio:number(.5,2,1.5),lodSplatCount:z.number().int().min(0).max(8000000).default(0),lodSplatScale:number(.25,2,1),lodRenderScale:number(1,5,1),maxSh:z.number().int().min(0).max(3).default(3),minSortIntervalMs:number(0,200,0),sortRadial:z.boolean().default(true),minPixelRadius:number(0,3,0),maxPixelRadius:number(64,1024,512),maxStdDev:number(2,3,Math.sqrt(8)),minAlpha:number(0,.1,.5/255),coneFov0:number(0,180,90),coneFov:number(0,180,120),coneFoveate:number(.1,1,.4),behindFoveate:number(.05,1,.2),xrFoveation:number(0,1,1)
}).strict().refine(s=>s.coneFov>=s.coneFov0,{message:'Outer detail angle must be at least the central angle.',path:['coneFov']});
export const PerformancePresetSchema=z.object({format:z.literal('spark-tour-performance-preset'),version:z.literal(1),name:z.string().trim().min(1).max(80),settings:PerformanceSettingsSchema}).strict();
export const PerformanceLibrarySchema=z.object({defaultPresetId:z.string(),presets:z.array(z.object({id:z.string().regex(/^[a-zA-Z0-9_-]+$/),name:z.string().trim().min(1).max(80),settings:PerformanceSettingsSchema}).strict()).min(1).max(100)}).strict().superRefine((v,c)=>{if(new Set(v.presets.map(p=>p.id)).size!==v.presets.length)c.addIssue({code:'custom',message:'Preset IDs must be unique.'});if(!v.presets.some(p=>p.id===v.defaultPresetId))c.addIssue({code:'custom',message:'Default performance preset is missing.'});});
export function defaultPerformance(){return {defaultPresetId:'balanced',presets:[{id:'balanced',name:'Balanced',settings:PerformanceSettingsSchema.parse({})},{id:'light',name:'Lightweight',settings:PerformanceSettingsSchema.parse({pixelRatio:1,lodSplatScale:.5,lodRenderScale:2,maxSh:1,minSortIntervalMs:16})},{id:'detail',name:'High detail',settings:PerformanceSettingsSchema.parse({pixelRatio:2,lodSplatScale:1.5})}]};}
export function presetFile(preset){return PerformancePresetSchema.parse({format:'spark-tour-performance-preset',version:1,name:preset.name,settings:preset.settings});}
