import {z} from 'zod';
import * as THREE from 'three';
const n=z.number().finite(),vec=z.tuple([n,n,n]);
const range=z.tuple([n,n]).refine(([a,b])=>a<b,'Minimum must be less than maximum');
export const ViewControlsSchema=z.object({type:z.enum(['photosphere','orbit','slider']).optional(),autoAnimate:z.boolean().optional(),animationSpeed:n.min(.01).max(1).optional(),orbit:z.object({center:vec,radius:n.min(.05).max(100000),azimuthBounds:range.optional(),elevationBounds:range.refine(([a,b])=>a>=-89&&b<=89,'Elevation must be within -89 and 89 degrees').optional()}).optional(),slider:z.object({origin:vec,rotation:vec,bounds:z.tuple([n.positive(),n.positive()]).optional()}).optional()});
export function defaultViewControls(view,type){const position=new THREE.Vector3(...view.position),q=new THREE.Quaternion().setFromEuler(new THREE.Euler(...view.rotation,'YXZ'));if(type==='orbit')return {type,orbit:{center:position.clone().add(new THREE.Vector3(0,0,-3).applyQuaternion(q)).toArray(),radius:3}};if(type==='slider')return {type,slider:{origin:[...view.position],rotation:[...view.rotation],bounds:[4,2]}};return {type:'photosphere'};}
export function sceneThumbnail(scene){return scene.thumbnailMode==='custom'||(!scene.thumbnailMode&&scene.thumbnail)?scene.thumbnail:scene.viewpoints.find(v=>v.id===scene.entry)?.thumbnail||'';}
const rad=THREE.MathUtils.degToRad,clamp=THREE.MathUtils.clamp;
export class ViewNavigation {
 constructor(view){this.view=structuredClone(view);this.type=view.type||'photosphere';this.phase=0;this.automatic=!!view.autoAnimate;this.position=new THREE.Vector3(...view.position);this.rotation=[...view.rotation];this.yaw=view.rotation[1];this.pitch=view.rotation[0];this.u=0;this.v=0;if(this.type==='orbit'&&view.orbit){const delta=this.position.clone().sub(new THREE.Vector3(...view.orbit.center));this.yaw=Math.atan2(delta.x,delta.z);this.pitch=Math.asin(clamp(delta.y/Math.max(delta.length(),.001),-1,1));const bounds=view.orbit.azimuthBounds;if(bounds){const middle=rad((bounds[0]+bounds[1])/2);this.yaw+=Math.round((middle-this.yaw)/(Math.PI*2))*Math.PI*2;}}if(this.type==='slider'&&view.slider){const delta=this.position.clone().sub(new THREE.Vector3(...view.slider.origin)).applyQuaternion(this.planeQuaternion().invert());this.u=delta.x;this.v=delta.y;}this.pose();this.startYaw=this.yaw;this.startPitch=this.pitch;const a=view.orbit?.azimuthBounds,b=view.orbit?.elevationBounds;this.yawPhase=a?Math.asin(clamp((this.yaw-rad((a[0]+a[1])/2))/rad((a[1]-a[0])/2),-1,1)):0;this.pitchPhase=b?Math.asin(clamp((this.pitch-rad((b[0]+b[1])/2))/rad((b[1]-b[0])/2),-1,1)):0;const bounds=view.slider?.bounds;this.uAmplitude=bounds?bounds[0]/2:Math.max(2,Math.abs(this.u)+.5);this.vAmplitude=bounds?bounds[1]/2:Math.max(1,Math.abs(this.v)+.5);this.uPhase=Math.asin(clamp(this.u/this.uAmplitude,-1,1));this.vPhase=Math.asin(clamp(this.v/this.vAmplitude,-1,1));}
 planeQuaternion(){return new THREE.Quaternion().setFromEuler(new THREE.Euler(...this.view.slider.rotation,'YXZ'));}
 takeControl(){this.automatic=false;}
 drag(dx,dy){this.takeControl();if(this.type==='slider'&&this.view.slider){this.u-=dx*.01;this.v+=dy*.01;}else{this.yaw-=dx*.003;this.pitch+=this.type==='orbit'?dy*.003:-dy*.003;}return this.pose();}
 animate(dt){if(!this.automatic)return null;this.phase+=dt*(this.view.animationSpeed||.08);if(this.type==='slider'&&this.view.slider){this.u=Math.sin(this.phase+this.uPhase)*this.uAmplitude;this.v=Math.sin(this.phase*.5+this.vPhase)*this.vAmplitude;}else if(this.type==='orbit'&&this.view.orbit){const a=this.view.orbit.azimuthBounds,b=this.view.orbit.elevationBounds;this.yaw=a?rad((a[0]+a[1])/2)+Math.sin(this.phase+this.yawPhase)*rad((a[1]-a[0])/2):this.startYaw+this.phase;this.pitch=b?rad((b[0]+b[1])/2)+Math.sin(this.phase*.35+this.pitchPhase)*rad((b[1]-b[0])/2):this.startPitch+Math.sin(this.phase*.5)*.08;}else{this.yaw=this.startYaw+this.phase;this.pitch=this.startPitch+Math.sin(this.phase*.5)*.08;}return this.pose();}
 pose(){let rotation=[...this.rotation],position=this.position.clone();if(this.type==='orbit'&&this.view.orbit){const o=this.view.orbit;this.pitch=clamp(this.pitch,rad(-89),rad(89));if(o.azimuthBounds)this.yaw=clamp(this.yaw,...o.azimuthBounds.map(rad));if(o.elevationBounds)this.pitch=clamp(this.pitch,...o.elevationBounds.map(rad));position.set(Math.sin(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),Math.cos(this.yaw)*Math.cos(this.pitch)).multiplyScalar(o.radius).add(new THREE.Vector3(...o.center));const matrix=new THREE.Matrix4().lookAt(position,new THREE.Vector3(...o.center),new THREE.Vector3(0,1,0)),e=new THREE.Euler().setFromRotationMatrix(matrix,'YXZ');rotation=[e.x,e.y,e.z];}else if(this.type==='slider'&&this.view.slider){const s=this.view.slider;if(s.bounds){this.u=clamp(this.u,-s.bounds[0]/2,s.bounds[0]/2);this.v=clamp(this.v,-s.bounds[1]/2,s.bounds[1]/2);}position.set(this.u,this.v,0).applyQuaternion(this.planeQuaternion()).add(new THREE.Vector3(...s.origin));}else{this.pitch=clamp(this.pitch,-1.5,1.5);rotation=[this.pitch,this.yaw,0];}return {position:position.toArray(),rotation};}
}
