import fs from 'node:fs/promises';import path from 'node:path';
await fs.mkdir('dist/licenses',{recursive:true});const list=[];const bundledPackages=new Set();const queue=['selfsigned','qrcode','@tiptap/react','@tiptap/pm','@tiptap/starter-kit','@tiptap/extension-image','@tiptap/extension-text-align'];while(queue.length){const name=queue.pop();if(bundledPackages.has(name))continue;bundledPackages.add(name);const pkg=JSON.parse(await fs.readFile(path.join('node_modules',name,'package.json'),'utf8'));queue.push(...Object.keys(pkg.dependencies||{}));}
await fs.copyFile('licenses/Google-Material-Symbols-LICENSE.txt','dist/licenses/Google-Material-Symbols-LICENSE.txt');
await fs.copyFile('LICENSE','dist/licenses/Spark-Tour-Studio-LICENSE.txt');await fs.copyFile('THIRD_PARTY.md','dist/licenses/THIRD_PARTY.md');
await fs.copyFile('collision-tools/Node-LICENSE.txt','dist/licenses/Node-LICENSE.txt');
for(const name of new Set(['@sparkjsdev/spark','three','@dimforge/rapier3d-compat','react','react-dom','zod','fflate','recast-navigation','@recast-navigation/core','@recast-navigation/generators','@recast-navigation/wasm',...bundledPackages])){const root=path.join('node_modules',name);const pkg=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));let text='';for(const file of await fs.readdir(root)){if(/^licen[sc]e|^copying|^notice/i.test(file)){const stat=await fs.stat(path.join(root,file));if(stat.isFile())text+=await fs.readFile(path.join(root,file),'utf8')+'\n';}}if(!text)text=`License identifier: ${pkg.license}. See ${pkg.repository?.url||pkg.homepage||name}.`;const target=name.replaceAll('/','_')+'.txt';await fs.writeFile(path.join('dist/licenses',target),`${name} ${pkg.version}\n\n${text}`);list.push({name,version:pkg.version,license:pkg.license});}
await fs.writeFile('dist/licenses/dependencies.json',JSON.stringify(list,null,2));

await fs.cp('specs/performance','dist/performance-spec',{recursive:true});
