import {_electron as electron,chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {plyFixture,radFixture,floorGlb} from '../tests/fixtures.mjs';import {blankProject,newScene} from '../shared/project.mjs';
const require=createRequire(import.meta.url),{startServer}=require('../desktop/server.cjs');
const root=path.resolve('test-output','polish-'+Date.now()),project=path.join(root,'project'),out=path.join(root,'export'),source=path.join(root,'source with spaces.ply');await fs.mkdir(path.join(project,'config'),{recursive:true});await fs.mkdir(out);await fs.writeFile(source,plyFixture());
const p=blankProject();p.scenes=[newScene('a','Atrium','test.rad'),newScene('b','Garden','test.rad')];p.startScene='a';p.scenes[0].collider='floor.glb';p.scenes[0].modes.push('explore');p.scenes[0].hotspots.push({id:'bubble',label:'About this place',position:[1,1.7,0],kind:'page',target:'story'});p.pages=[{id:'story',title:'A story',html:'',blocks:[{type:'text',text:'A round bubble opens this page.',url:''}]}];
await fs.writeFile(path.join(project,'test.rad'),radFixture().rad);await fs.writeFile(path.join(project,'floor.glb'),floorGlb());await fs.writeFile(path.join(project,'config/tour.json'),JSON.stringify(p));await fs.writeFile(path.join(project,'config/hosting.json'),'{}');
const app=await electron.launch({...process.env.SPARK_PACKAGED?{executablePath:path.resolve('release/win-unpacked/Spark Tour Studio.exe'),args:[]}:{args:['.']},env:{...process.env,SPARK_TEST:'1'},timeout:60000});
try{
 const page=await app.firstWindow();await page.waitForSelector('.studio');const choose=async file=>app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({filePaths:[file],canceled:false});},file);
 await choose(project);await page.getByRole('button',{name:'Open',exact:true}).click();await page.locator('.scene-card').first().waitFor();
 await page.getByRole('button',{name:'Delete scene Garden',exact:true}).click();await page.locator('.dialog').getByRole('button',{name:'Delete scene',exact:true}).click();await expect(page.locator('.scene-card')).toHaveCount(1);await page.getByTitle('Undo',{exact:true}).click();await expect(page.locator('.scene-card')).toHaveCount(2);
 await page.getByRole('button',{name:'⌖ Capture viewpoint',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Saved project',{exact:true}).waitFor();let saved=JSON.parse(await fs.readFile(path.join(project,'config/tour.json')));assert.equal(saved.scenes[0].viewpoints.length,2);assert.match(saved.scenes[0].viewpoints[1].thumbnail,/^data:image\/jpeg/);await page.screenshot({path:path.join(root,'viewpoints.png')});
 await page.locator('.inspector-tabs').getByRole('button',{name:'scene',exact:true}).click();await page.getByRole('button',{name:'Generate collision mesh…'}).click();await choose(source);await page.getByRole('button',{name:'Choose PLY & generate'}).click();await Promise.race([page.locator('.dialog').waitFor({state:'hidden',timeout:60000}),page.getByText(/See collision-logs/).waitFor({timeout:60000}).then(async()=>{throw Error(await page.locator('.dialog').innerText());})]);await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Saved project',{exact:true}).waitFor();saved=JSON.parse(await fs.readFile(path.join(project,'config/tour.json')));assert.match(saved.scenes[0].collider,/assets\/collisions\/.*\.collision\.glb/);assert.deepEqual(await fs.readFile(source),plyFixture());
 // Verify the generated mesh uses the same Y axis as the source, rather than the tool's PLY flip.
 const glb=await fs.readFile(path.join(project,saved.scenes[0].collider)),gltf=JSON.parse(glb.subarray(20,20+glb.readUInt32LE(12)).toString());assert.ok(gltf.accessors[gltf.meshes[0].primitives[0].attributes.POSITION].min[1]>0);
 await page.screenshot({path:path.join(root,'collision.png')});
 // Restore the floor with undo so the exported navigation check has a walkable fixture.
 await page.getByTitle('Undo',{exact:true}).click();await choose(out);await page.getByRole('button',{name:'Export tour ↗'}).click();await page.getByRole('button',{name:'Choose folder & export'}).click();await page.locator('.dialog').waitFor({state:'hidden',timeout:90000});assert.ok((await fs.readdir(path.join(out,'assets'))).some(n=>n.startsWith('navigation.worker')));
 console.log('PASS: scene delete/undo, captured thumbnail persistence, bundled GPU collision generation/alignment, portable export.');
}catch(e){console.error(e);throw e;}finally{await app.evaluate(({BrowserWindow})=>{for(const w of BrowserWindow.getAllWindows())w.destroy();}).catch(()=>{});await app.close();}
const {server,url}=await startServer({root:out});const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const page=await browser.newPage({viewport:{width:1280,height:800}}),external=[];await page.route('**/*',route=>{if(route.request().url().startsWith(url))return route.continue();external.push(route.request().url());return route.abort();});await page.goto(url+'?diagnostics=1');await page.getByRole('button',{name:'Enter tour ↗'}).click();await page.waitForFunction(()=>window.tourRuntime?.routes.ready);await page.evaluate(()=>window.tourRuntime.setMode('explore'));await page.waitForFunction(()=>window.tourRuntime.mode==='explore');
 await page.evaluate(()=>{const r=window.tourRuntime;r.walkTo({x:3,y:0,z:0});});await page.waitForFunction(()=>window.tourRuntime.routes.points.length>0);await page.waitForFunction(()=>window.tourRuntime.rig.position.x>2.8,{},{timeout:15000});await page.waitForFunction(()=>window.tourRuntime.routes.points.length===0);assert.equal(await page.locator('.status').count(),0);
 await page.evaluate(()=>window.tourRuntime.walkTo({x:200,y:0,z:200}));await page.waitForTimeout(300);assert.equal(await page.locator('.status').count(),0);assert.equal(await page.evaluate(()=>window.tourRuntime.routes.points.length),0);
 await page.evaluate(()=>window.tourRuntime.walkTo({x:-4,y:0,z:-4}));await page.waitForFunction(()=>window.tourRuntime.routes.points.length>0);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.tourRuntime.routes.points.length),0);
 assert.deepEqual(external,[]);await page.screenshot({path:path.join(root,'viewer.png')});
 // Menu rendering and exit guarding without claiming a real headset session test.
 const menu=await page.evaluate(()=>{const r=window.tourRuntime;r.renderer.setAnimationLoop(null);r.renderer.xr.isPresenting=true;r.renderer.xr.getCamera=()=>r.camera;r.menuOpen=true;r.refreshHud(true);const opaque=r.hud.children.every(c=>!c.material?.transparent),before=r.confirmExit;const exit=r.hud.children.find(c=>c.userData.action&&Math.abs(c.position.y+.98)<.01);exit.userData.action();const after=r.confirmExit;r.renderer.xr.isPresenting=false;r.fade.visible=false;r.renderer.render(r.scene,r.camera);r.renderer.autoClear=false;r.renderer.clearDepth();r.renderer.render(r.overlay,r.camera);return {opaque,before,after};});assert.deepEqual(menu,{opaque:false,before:false,after:true});await page.screenshot({path:path.join(root,'vr-menu.png')});const teleport=await page.evaluate(()=>{const r=window.tourRuntime;r.renderer.xr.isPresenting=true;r.menuOpen=false;r.hud.visible=false;r.viewMarkers.visible=false;for(const b of r.bubbles.children)b.visible=false;const c=r.controllers[0];c.position.set(0,0,0);c.rotation.set(-Math.PI/4,0,0);c.updateMatrix();r.scene.updateMatrixWorld(true);const before=r.rig.position.z;r.triggerStart(c);const aimed=!!r.teleportPoint;r.triggerEnd(c);const after=r.rig.position.z;r.renderer.xr.isPresenting=false;return {aimed,before,after};});assert.ok(teleport.aimed&&teleport.after<teleport.before-.5,JSON.stringify(teleport));console.log('PASS: trigger hold/release teleports to collision floor.');console.log('PASS: offline exported worker, walk to destination, silent unreachable click, Escape cancel, translucent XR menu and guarded exit. '+root);
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
