import {radFixture} from '../tests/fixtures.mjs';
import {chromium,_electron as electron} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {startServer}=require('../desktop/server.cjs');const root=path.resolve('test-output',`smoke-${Date.now()}`);await fs.mkdir(root,{recursive:true});const projectPath=path.join(root,'project');await fs.mkdir(projectPath);
const app=await electron.launch({...(process.env.SPARK_PACKAGED?{executablePath:path.resolve('release/win-unpacked/Spark Tour Studio.exe'),args:[]}:{args:['.']}),env:{...process.env,SPARK_TEST:'1'},timeout:60000});
try{const page=await app.firstWindow();await page.waitForSelector('.studio');const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.screenshot({path:path.join(root,'editor-welcome.png')});
 const selectFolder=async folder=>app.evaluate(({dialog},folder)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]});},folder);
 await selectFolder(projectPath);await page.getByRole('button',{name:'New',exact:true}).click();await page.getByText('Saved project',{exact:true}).waitFor();await page.getByRole('button',{name:'＋ Add hosted scene'}).click();await page.getByLabel('Name',{exact:true}).fill('Exterior grounds');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Saved project',{exact:true}).waitFor();
 await page.getByRole('button',{name:'▤ Content pages'}).click();await page.getByRole('button',{name:'＋ New page'}).click();await page.getByLabel('Page title').fill('The story');await page.getByLabel('Block text or caption').fill('A locally bundled story for this tour.');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Saved project',{exact:true}).waitFor();
 await page.screenshot({path:path.join(root,'editor-project.png')});const saved=JSON.parse(await fs.readFile(path.join(projectPath,'config','tour.json'),'utf8'));assert.equal(saved.scenes[0].name,'Exterior grounds');assert.equal(saved.pages[0].title,'The story');assert.equal(saved.pages[0].blocks[0].text,'A locally bundled story for this tour.');assert.deepEqual(errors,[]);
 const out=path.join(root,'export');await fs.mkdir(out);await selectFolder(out);await page.getByRole('button',{name:'Export tour ↗'}).click();await page.getByLabel('Asset delivery').selectOption('referenced');await page.getByRole('button',{name:'Choose folder & export'}).click();await page.getByText(/Export complete:/).waitFor({timeout:120000});assert.ok(await fs.stat(path.join(out,'Launch Tour.exe')));
 const {server,url}=await startServer({root:out});const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const context=await browser.newContext({viewport:{width:1440,height:900}});await context.route('**/*',route=>route.request().url().startsWith(url)?route.continue():route.abort());const viewer=await context.newPage();const viewErrors=[];viewer.on('console',m=>{if(m.type()==='error')console.log('Browser console:',m.text());});viewer.on('pageerror',e=>viewErrors.push(e.message));await viewer.goto(url);await viewer.getByRole('button',{name:'Enter tour ↗'}).waitFor();await viewer.screenshot({path:path.join(root,'viewer-title.png')});await viewer.getByRole('button',{name:'Enter tour ↗'}).click();await viewer.getByRole('button',{name:'Retry',exact:true}).waitFor({timeout:30000});await viewer.getByRole('button',{name:'Home',exact:true}).click();await viewer.getByRole('button',{name:'Enter tour ↗'}).waitFor();assert.deepEqual(viewErrors,[]); const fixture=radFixture(); await fs.writeFile(path.join(out,'fixture.rad'),fixture.rad); const config=JSON.parse(await fs.readFile(path.join(out,'config','tour.json'),'utf8')); config.scenes[0].source='fixture.rad'; config.scenes.push({...structuredClone(config.scenes[0]),id:'second',name:'Second scene'}); await fs.writeFile(path.join(out,'config','tour.json'),JSON.stringify(config)); await viewer.reload(); await viewer.getByRole('button',{name:'Enter tour ↗'}).click(); await viewer.locator('.status').waitFor({state:'hidden',timeout:30000}); await viewer.waitForTimeout(2000); await viewer.screenshot({path:path.join(root,'viewer-synthetic-rad.png')}); await viewer.getByLabel('Scene',{exact:true}).selectOption('second'); await viewer.locator('.status').waitFor({state:'hidden',timeout:30000}); await viewer.getByLabel('Scene',{exact:true}).selectOption(config.scenes[0].id); await viewer.locator('.status').waitFor({state:'hidden',timeout:30000}); assert.deepEqual(viewErrors,[]); console.log('Editor save/export and bundled viewer smoke passed. Artifacts: '+root);}finally{await browser.close();await new Promise(r=>server.close(r));}
}finally{await app.close();}
