import * as THREE from 'three';
import {getHtmlRenderer,installHtmlInCanvasPolyfill} from 'three-html-render/polyfill';
import {VRButton} from 'three/addons/webxr/VRButton.js';
// Development-only feasibility page. No promotion into the shipped viewer without headset QA.
document.body.style.cssText='margin:0;background:#10232b;color:white;font:16px system-ui';
const element=document.createElement('div');element.style.cssText='position:absolute;left:-10000px;top:0;width:512px;height:360px;padding:24px;background:#204438;color:white;font:22px system-ui';element.innerHTML='<h1>Local HTML panel</h1><p>Candidate renderer: three-html-render 0.1.2</p><button>Controller click target</button><p>Rich HTML remains experimental until real-headset input and performance checks pass.</p>';document.body.appendChild(element);
const status=document.createElement('p');status.style.cssText='position:absolute;top:0;left:20px';status.textContent='Rendering local HTML…';document.body.appendChild(status);
installHtmlInCanvasPolyfill();const renderer=new THREE.WebGLRenderer();renderer.setSize(innerWidth,innerHeight);renderer.xr.enabled=true;document.body.appendChild(renderer.domElement);document.body.appendChild(VRButton.createButton(renderer));const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,100);camera.position.z=2;
try{const canvas=await getHtmlRenderer().update(element);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(1.5,1),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide}));scene.add(mesh);status.textContent=`HTML rendered: ${canvas.width} × ${canvas.height}. Headset acceptance remains pending.`;for(let i=0;i<2;i++){const controller=renderer.xr.getController(i);scene.add(controller);controller.addEventListener('select',()=>{status.textContent='XR select received. Full DOM interaction requires a dedicated bridge.';});}renderer.setAnimationLoop(()=>renderer.render(scene,camera));}catch(e){status.textContent='Prototype failed: '+String(e);}
