import {BackgroundLayer} from './background';
import {PerformanceSettingsSchema} from '../shared/performance.mjs';
import type {PerformanceSettings} from './model';
import * as THREE from 'three';
import { SparkRenderer, SplatMesh } from '@sparkjsdev/spark';
import RAPIER from '@dimforge/rapier3d-compat';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { TransformControls } from 'three/addons/controls/TransformControls.js';
import type { Project,TourScene,Hosting,Mode,Viewpoint,Hotspot,Page,Transform,Vec3 } from './model';
import {flyMovement,nearbyFlyPosition} from '../shared/flying.mjs';
import { characterMovement,nearbyWalkingFeet } from '../shared/walking.mjs';
import { sceneUrl } from '../shared/project.mjs';
import { assertPagedRad } from '../shared/rad.mjs';
import {xrMotion} from '../shared/xr-controls.mjs';
import {badge,panel,releaseUI} from './spatial-ui';
import {TourAudio} from './tour-audio';
import {ViewNavigation} from '../shared/viewpoints.mjs';
import {ViewGeometry} from './view-geometry';
import {WalkingRoutes} from './walking-routes';

const physicsReady=RAPIER.init();
const v=(a:Vec3)=>new THREE.Vector3(...a);
function apply(o:THREE.Object3D,t:Transform){o.position.fromArray(t.position);o.rotation.set(...t.rotation,'YXZ');o.scale.setScalar(t.scale);o.updateMatrixWorld(true);}
function release(o:THREE.Object3D){o.traverse(c=>{if(c instanceof THREE.Mesh){c.geometry.dispose();for(const m of Array.isArray(c.material)?c.material:[c.material]){(m as THREE.MeshBasicMaterial).map?.dispose();m.dispose();}}});o.removeFromParent();}
function label(text:string,width=768,height=128,bg='#16323a'){
 const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const c=canvas.getContext('2d')!;
 c.fillStyle=bg;c.fillRect(0,0,width,height);c.strokeStyle='#579e94';c.lineWidth=3;c.strokeRect(2,2,width-4,height-4);c.fillStyle='#ecf7f3';c.font='32px system-ui';
 const words=text.split(/\s+/);let line='',y=48;for(const w of words){if(c.measureText(line+w).width>width-40){c.fillText(line,20,y);line='';y+=42;}line+=w+' ';}c.fillText(line,20,y);
 const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;return tex;
}
function textPages(page:Page){return page.blocks.flatMap(b=>{if(b.type!=='text')return [b];const words=b.text.split(/\s+/),pages:string[]=[];let text='';for(const word of words){if(text.length+word.length>420){pages.push(text);text='';}text+=word+' ';}if(text)pages.push(text);return pages.map(text=>({...b,text}));});}
export class TourRuntime {
 readonly viewGeometry=new ViewGeometry();private navigator?:ViewNavigation;private viewXROffset=new THREE.Vector3();private thumbnailPending?:{id:string;after:number};onViewpointThumbnail=(id:string,data:string)=>{};onViewGeometry=(id:string,patch:Partial<Viewpoint>)=>{};
 readonly audio=new TourAudio();private flight?:{start:number;duration:number;from:THREE.Vector3;to:THREE.Vector3;fromYaw:THREE.Quaternion;toYaw:THREE.Quaternion;pitch:number;targetPitch:number};private descriptionLabel?:THREE.Mesh;
 readonly overlay=new THREE.Scene();readonly viewMarkers=new THREE.Group();readonly routes=new WalkingRoutes(this.overlay);readonly renderer:THREE.WebGLRenderer;readonly scene=new THREE.Scene();readonly camera=new THREE.PerspectiveCamera(65,1,.05,20000);readonly rig=new THREE.Group();readonly content=new THREE.Group();readonly bubbles=new THREE.Group();readonly hud=new THREE.Group();readonly spark:SparkRenderer;readonly gizmo:TransformControls;
 private lastViewpoints=new Map<string,string>();currentViewpoint='';showViewpoints=false;swapSticks=false;xrFly=true;onViewpoint=(id:string)=>{};
 private menuRecenterFrames=0;private menuOpen=false;private menuTab:'move'|'scenes'|'views'|'options'='move';private menuPage=0;private confirmExit=false;private held=new Map<THREE.Object3D,THREE.Object3D|null>();private teleportController?:THREE.XRTargetRaySpace;private teleportPoint?:THREE.Vector3;private aimTime=0;private hovered?:THREE.Object3D;private routeStall=0;private lastSafeHead?:THREE.Vector3;private menuAnchor=new THREE.Vector3();private wristMenu=badge('☰','Tour menu');private teleportRing=new THREE.Mesh(new THREE.RingGeometry(.17,.25,48),new THREE.MeshBasicMaterial({color:0x9fffc8,side:THREE.DoubleSide,depthTest:false,depthWrite:false}));
 project:Project|null=null;hosting:Hosting={assetBaseUrl:'./',sceneUrls:{}};base=location.href;active:TourScene|null=null;mode:Mode='jumps';viewHeight=1.7;speed=2;quality=1;performanceSettings:PerformanceSettings=PerformanceSettingsSchema.parse({});frameMs=16;snap=true;editing=false;blocked=false;
 onStatus=(text:string,error=false)=>{};onScene=(id:string)=>{};onMode=(mode:Mode)=>{};onPage=(page:Page)=>{};onPick=(point:Vec3)=>{};onSelect=(id:string)=>{};onMove=(id:string,point:Vec3)=>{};
 private backgroundLayer=new BackgroundLayer(this.scene,message=>this.report(message,true));private mesh?:SplatMesh;private collider?:THREE.Group;private world?:RAPIER.World;private body?:RAPIER.RigidBody;private character?:RAPIER.KinematicCharacterController;private capsule?:RAPIER.Collider;private generation=0;private dead=false;private keys=new Set<string>();private observers:ResizeObserver;private cleanup:(()=>void)[]=[];private ray=new THREE.Raycaster();private touch=new THREE.Vector2();private pointerMove=new THREE.Vector3();private last=0;private velocityY=0;private crouched=false;private touchCrouch=false;private touchLift=0;private jumpRequested=false;private turnReady=true;private status='';private hudPage=0;private currentPage:Page|null=null;private selected?:THREE.Object3D;private fade:THREE.Mesh;private fadeUntil=0;private controllers:THREE.XRTargetRaySpace[]=[];private pendingPick=false;
 constructor(readonly host:HTMLElement){
  this.renderer=new THREE.WebGLRenderer({antialias:false,alpha:false,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.xr.enabled=true;this.renderer.xr.setReferenceSpaceType('local-floor');this.renderer.setClearColor('#0b151d');this.renderer.domElement.tabIndex=0;host.appendChild(this.renderer.domElement);
  this.spark=new SparkRenderer({renderer:this.renderer,lodSplatScale:1,maxPagedSplats:8388608});this.applyPerformance(this.performanceSettings);this.scene.add(this.spark,this.content,this.rig);this.content.add(this.viewGeometry.group);this.overlay.add(this.bubbles,this.viewMarkers,this.hud,this.wristMenu,this.teleportRing);this.wristMenu.visible=false;this.wristMenu.userData.action=()=>this.toggleMenu();this.teleportRing.rotation.x=-Math.PI/2;this.teleportRing.visible=false;this.routes.onNotice=text=>this.onStatus(text,false);this.rig.rotation.order='YXZ';this.rig.add(this.camera);this.rig.position.set(0,1.7,3);
  const grid=new THREE.GridHelper(30,30,0x2d706e,0x18333c);grid.name='empty-grid';this.scene.add(grid);
  this.fade=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:0,depthTest:false,depthWrite:false,side:THREE.DoubleSide}));this.fade.renderOrder=10000;this.overlay.add(this.fade);
  this.gizmo=new TransformControls(this.camera,this.renderer.domElement);this.scene.add(this.gizmo.getHelper());this.gizmo.addEventListener('dragging-changed',e=>{this.blocked=!!e.value;});this.gizmo.addEventListener('mouseUp',()=>{if(this.selected?.userData.geometryHandle&&this.viewGeometry.view){this.onViewGeometry(this.viewGeometry.view.id,this.viewGeometry.patch(this.selected));return;}if(this.selected)this.onMove(this.selected.userData.id,this.selected.position.toArray() as Vec3);});
  const on=(target:EventTarget,name:string,fn:EventListener)=>{target.addEventListener(name,fn);this.cleanup.push(()=>target.removeEventListener(name,fn));};
  on(window,'keydown',((e:KeyboardEvent)=>{this.audio.unlock();if((e.target as HTMLElement)?.closest('input,textarea,select,[contenteditable]'))return;if(!e.repeat&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyQ','KeyE','Space'].includes(e.code))this.navigator?.takeControl();if(e.code==='Space'&&!e.repeat)this.requestJump();this.keys.add(e.code);if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){this.stopFlight();this.keys.clear();this.routes.cancel();this.currentPage=null;this.menuOpen=false;this.refreshHud();}}) as EventListener);
  on(window,'keyup',((e:KeyboardEvent)=>{this.keys.delete(e.code);}) as EventListener);on(window,'blur',()=>{this.keys.clear();this.setTouch(0,0);this.touchLift=0;this.touchCrouch=false;this.jumpRequested=false;});
  let start={x:0,y:0},down=false,moved=false,dragButton=0,dragPointer=-1;
  const endDrag=()=>{down=false;dragPointer=-1;};on(window,'blur',()=>{endDrag();this.pointerMove.set(0,0,0);});on(window,'pointercancel',endDrag);
  on(this.renderer.domElement,'contextmenu',e=>e.preventDefault());
  on(this.renderer.domElement,'pointerdown',((e:PointerEvent)=>{if(down||(e.button!==0&&e.button!==2))return;if(e.button===2)e.preventDefault();this.audio.unlock();this.renderer.domElement.focus();start={x:e.clientX,y:e.clientY};down=true;moved=false;dragButton=e.button;dragPointer=e.pointerId;}) as EventListener);
  on(window,'pointermove',((e:PointerEvent)=>{if(e.target===this.renderer.domElement&&!this.renderer.xr.isPresenting){this.pointerRay(e);this.highlight(this.hitUI());}if(!down||e.pointerId!==dragPointer||this.blocked||this.renderer.xr.isPresenting||this.gizmo.dragging)return;if(!(e.buttons&(dragButton===2?2:1))){endDrag();return;}const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)+Math.abs(dy)>2){moved=true;if(!(this.mode==='jumps'&&!this.editing&&this.navigator))this.stopFlight();}start={x:e.clientX,y:e.clientY};if(this.mode==='jumps'&&!this.editing&&this.navigator){this.steerView(this.navigator.drag(dx,dy));return;}if(dragButton===2){const scale=2*this.speed/Math.max(1,this.host.clientHeight);this.pointerMove.add(new THREE.Vector3(-dx,dy,0).applyQuaternion(this.camera.getWorldQuaternion(new THREE.Quaternion())).multiplyScalar(scale));}else{this.rig.rotation.y-=dx*.003;this.camera.rotation.x=THREE.MathUtils.clamp(this.camera.rotation.x-dy*.003,-1.5,1.5);}}) as EventListener);
  on(window,'pointerup',((e:PointerEvent)=>{if(!down||e.pointerId!==dragPointer||e.button!==dragButton)return;if(dragButton===0&&!moved&&!this.gizmo.dragging&&e.target===this.renderer.domElement)this.click(e);endDrag();}) as EventListener);
  const wheel=(e:WheelEvent)=>{e.preventDefault();if(this.blocked||this.gizmo.dragging||this.renderer.xr.isPresenting)return;this.audio.unlock();this.navigator?.takeControl();if(this.mode==='jumps'&&!this.editing)return;const pixels=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?this.host.clientHeight:1);this.pointerMove.add(this.camera.getWorldDirection(new THREE.Vector3()).multiplyScalar(-THREE.MathUtils.clamp(pixels,-300,300)*this.speed*.002));};this.renderer.domElement.addEventListener('wheel',wheel,{passive:false});this.cleanup.push(()=>this.renderer.domElement.removeEventListener('wheel',wheel));
  for(let i=0;i<2;i++){const controller=this.renderer.xr.getController(i);this.rig.add(controller);this.controllers.push(controller);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-12)]),new THREE.LineBasicMaterial({color:0xa8e6d4,transparent:true,opacity:.65}));this.overlay.add(line);line.visible=false;controller.userData.rayLine=line;const tip=new THREE.Mesh(new THREE.SphereGeometry(.008,12,8),new THREE.MeshBasicMaterial({color:0x669ab5,depthTest:false,depthWrite:false}));tip.renderOrder=200;tip.visible=false;controller.userData.tip=tip;this.overlay.add(tip);controller.addEventListener('connected',event=>{controller.userData.handedness=event.data.handedness;});controller.addEventListener('squeezestart',()=>this.toggleMenu());controller.addEventListener('selectstart',()=>this.triggerStart(controller));controller.addEventListener('selectend',()=>this.triggerEnd(controller));}
  this.renderer.xr.addEventListener('sessionstart',()=>{this.renderer.xr.setFoveation(this.performanceSettings.xrFoveation);this.viewXROffset.set(0,0,0);this.stopFlight();this.keys.clear();this.blocked=false;this.routes.cancel();this.camera.position.set(0,0,0);this.camera.rotation.set(0,0,0);this.rig.position.y-=this.mode==='explore'?this.walkEyeHeight:1.7;this.menuOpen=true;this.menuRecenterFrames=2;this.menuTab='move';this.confirmExit=false;this.refreshHud(true);this.onMode(this.mode);});
  this.renderer.xr.addEventListener('sessionend',()=>{this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.performanceSettings.pixelRatio));this.stopFlight();const head=this.camera;const pos=head.getWorldPosition(new THREE.Vector3()),e=new THREE.Euler().setFromQuaternion(head.getWorldQuaternion(new THREE.Quaternion()),'YXZ');this.rig.position.copy(pos);this.rig.rotation.set(0,e.y,0);this.camera.position.set(0,0,0);this.camera.rotation.set(e.x,0,0);this.menuOpen=false;this.hud.visible=false;this.wristMenu.visible=false;this.cancelTeleport();this.held.clear();this.routes.cancel();if(this.body){if(this.mode==='explore'){const body=this.body.translation();this.rig.position.y=body.y-(this.crouched?.55:.85)+this.walkEyeHeight;}else this.body.setTranslation({x:pos.x,y:pos.y-.85,z:pos.z},true);}});
  this.observers=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();});this.observers.observe(host);
  this.renderer.setAnimationLoop(t=>this.frame(t));
  if(new URLSearchParams(location.search).has('diagnostics'))(window as unknown as {tourRuntime:TourRuntime}).tourRuntime=this;
 }
 async load(project:Project,hosting:Hosting,base:string,sceneId?:string){this.project=project;this.hosting=hosting;this.base=base;await this.selectScene(sceneId||project.startScene);}
 unload(){++this.generation;this.clearScene();this.active=null;this.status='';this.scene.getObjectByName('empty-grid')!.visible=true;}
 private report(text:string,error=false){this.status=text;this.onStatus(text,error);if(this.renderer.xr.isPresenting){if(error)this.menuOpen=true;this.refreshHud(error);}}
 private clearScene(){this.backgroundLayer.clear();this.navigator=undefined;this.thumbnailPending=undefined;this.viewGeometry.clear();this.crouched=false;this.jumpRequested=false;this.touchCrouch=false;this.touchLift=0;this.setTouch(0,0);this.pointerMove.set(0,0,0);this.flight=undefined;this.audio.stop();this.descriptionLabel&&releaseUI(this.descriptionLabel);this.descriptionLabel=undefined;this.lastSafeHead=undefined;this.routes.dispose();this.cancelTeleport();this.held.clear();this.currentViewpoint='';this.onViewpoint('');for(const c of [...this.viewMarkers.children])releaseUI(c);this.gizmo.detach();this.selected=undefined;if(this.mesh){this.mesh.removeFromParent();this.mesh.dispose();this.mesh=undefined;}if(this.collider){release(this.collider);this.collider=undefined;}for(const c of [...this.bubbles.children])release(c);this.world?.free();this.world=undefined;this.body=undefined;this.character=undefined;this.capsule=undefined;}
 async selectScene(id:string,viewpoint?:string){
  const s=this.project?.scenes.find(x=>x.id===id);if(!s){this.report('Choose a scene to begin.',true);return;}
  const token=++this.generation;this.clearScene();this.active=s;this.mode='jumps';this.setViewHeight(s.walkHeight??1.7);this.onMode(this.mode);this.currentPage=null;this.report(`Loading ${s.name}…`);this.onScene(id);this.scene.getObjectByName('empty-grid')!.visible=false;apply(this.content,s.transform);this.bubbles.position.copy(this.content.position);this.bubbles.quaternion.copy(this.content.quaternion);this.bubbles.scale.copy(this.content.scale);this.viewMarkers.position.copy(this.content.position);this.viewMarkers.quaternion.copy(this.content.quaternion);this.viewMarkers.scale.copy(this.content.scale);
  try{
   if(!s.source)throw new Error('Choose a RAD file or URL for this scene.');
   let streamError:unknown;const mesh=new SplatMesh({url:sceneUrl(s,this.hosting,this.base),paged:true});this.mesh=mesh;mesh.maxSh=this.performanceSettings.maxSh;
   if(mesh.paged){const paged=mesh.paged,decode=paged.fetchDecodeChunk.bind(paged);let reported=false;paged.fetchDecodeChunk=async chunk=>{try{return await decode(chunk);}catch(e){if(!reported&&token===this.generation&&!this.dead){reported=true;streamError=e;paged.abortController.abort();mesh.visible=false;this.report(`Streaming failed: ${String(e)}. Retry the scene.`,true);}throw e;}};}
   await mesh.initialized;const rad=await mesh.paged?.getRadMeta();if(token!==this.generation||this.dead)return;if(rad)assertPagedRad(rad.meta);this.content.add(mesh);
   await this.setBackground(this.active?.id===s.id?this.active.background:s.background);if(token!==this.generation||this.dead)return;
   if(s.collider)await this.loadCollider(s,token);if(token!==this.generation||this.dead)return;
   if(streamError)throw streamError;this.rebuildHotspots();if(!this.editing)this.audio.setScene(s.audio,this.base);this.jump(viewpoint||s.entry,false);this.report('');const mode=s.modes.includes('jumps')?'jumps':s.modes.includes('fly')?'fly':'explore';if(mode==='explore')this.setMode(mode,true);else{this.mode=mode;this.onMode(mode);}
  }catch(e){if(token===this.generation&&!this.dead){this.clearScene();this.report(`${s.name}: ${e instanceof Error?e.message:e}`,true);}}
 }
 private async loadCollider(s:TourScene,token:number){
  await physicsReady;const gltf=await new GLTFLoader().loadAsync(new URL(s.collider,this.base).href);if(token!==this.generation||this.dead){release(gltf.scene);return;}
  const root=gltf.scene;apply(root,s.colliderTransform);this.content.add(root);this.content.updateMatrixWorld(true);this.collider=root;this.world=new RAPIER.World({x:0,y:-9.81,z:0});
  const navigationParts:{positions:Float32Array;indices:Uint32Array}[]=[];root.traverse(o=>{if(!(o instanceof THREE.Mesh))return;const pos=o.geometry.getAttribute('position');if(!pos)return;const verts=new Float32Array(pos.count*3);for(let i=0;i<pos.count;i++){const pt=new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(o.matrixWorld);verts.set(pt.toArray(),i*3);}const indices=o.geometry.index?new Uint32Array(o.geometry.index.array):Uint32Array.from({length:pos.count},(_,i)=>i);this.world!.createCollider(RAPIER.ColliderDesc.trimesh(verts,indices));navigationParts.push({positions:verts,indices});for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();o.material=new THREE.MeshBasicMaterial({color:0x77efd3,wireframe:true,transparent:true,opacity:.45});});root.visible=false;
  this.body=this.world.createRigidBody(RAPIER.RigidBodyDesc.kinematicPositionBased());this.capsule=this.world.createCollider(RAPIER.ColliderDesc.capsule(.6,.25),this.body);this.character=this.world.createCharacterController(.015);this.character.enableAutostep(.25,.2,false);this.character.enableSnapToGround(.3);this.character.setMaxSlopeClimbAngle(Math.PI/4);this.character.setMinSlopeSlideAngle(Math.PI/4);this.world.step();this.routes.build(navigationParts);
 }
 setBackground(value:TourScene['background']){return this.backgroundLayer.load(value,this.base,this.hosting,this.performanceSettings.maxSh);}
 showCollider(show:boolean){if(this.collider)this.collider.visible=show;}
 applyPerformance(value:PerformanceSettings){const s=PerformanceSettingsSchema.parse(value);this.performanceSettings=s;const {pixelRatio,maxSh,xrFoveation,lodSplatCount,...sparkSettings}=s;Object.assign(this.spark,sparkSettings);this.spark.lodSplatCount=lodSplatCount||undefined;this.quality=s.lodSplatScale;if(!this.renderer.xr.isPresenting)this.renderer.setPixelRatio(Math.min(devicePixelRatio,pixelRatio));this.renderer.xr.setFoveation(xrFoveation);if(this.mesh&&this.mesh.maxSh!==maxSh){this.mesh.maxSh=maxSh;this.mesh.generatorDirty=true;}this.mesh?.updateVersion();this.backgroundLayer.performance(maxSh);this.spark.dirty=true;}
 setQuality(q:number){this.applyPerformance({...this.performanceSettings,lodSplatScale:q});}
 setTouch(x:number,y:number){if(Math.abs(x)+Math.abs(y)>.01)this.navigator?.takeControl();this.touch.set(THREE.MathUtils.clamp(x,-1,1),THREE.MathUtils.clamp(y,-1,1));}
 private get walkEyeHeight(){return this.viewHeight-(this.crouched?.6:0);}
 setViewHeight(value:number){if(!Number.isFinite(value))return;const next=THREE.MathUtils.clamp(value,1,2.4),delta=next-this.viewHeight;this.viewHeight=next;if(this.mode==='explore'&&!this.renderer.xr.isPresenting)this.rig.position.y+=delta;}
 setTouchLift(value:number){this.touchLift=value;}
 setTouchCrouch(value:boolean){this.touchCrouch=value;}
 requestJump(){if(this.mode==='explore'&&!this.blocked){this.jumpRequested=true;this.routes.cancel();}}
 private updateCrouch(wanted:boolean,force=false){if(wanted===this.crouched||!this.world||!this.body||!this.capsule)return;const old=this.body.translation(),delta=wanted?-.3:.3,center={x:old.x,y:old.y+delta,z:old.z};if(!wanted&&!force&&this.world.intersectionWithShape(center,{x:0,y:0,z:0,w:1},new RAPIER.Capsule(.58,.24),undefined,undefined,this.capsule))return;this.capsule.setShape(new RAPIER.Capsule(wanted?.3:.6,.25));this.body.setTranslation(center,true);this.world.step();this.rig.position.y+=wanted?-.6:.6;this.crouched=wanted;}

 setEditing(editing:boolean){if(this.editing===editing)return;this.stopFlight();if(!editing&&this.navigator){const pose=this.navigator.pose(),point=this.content.localToWorld(new THREE.Vector3(...pose.position)),rotation=this.content.getWorldQuaternion(new THREE.Quaternion()).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(pose.rotation[0],pose.rotation[1],pose.rotation[2],'YXZ')));if(point.distanceTo(this.camera.getWorldPosition(new THREE.Vector3()))>.03||rotation.angleTo(this.camera.getWorldQuaternion(new THREE.Quaternion()))>.03){this.navigator=undefined;this.currentViewpoint='';this.onViewpoint('');}}this.editing=editing;}
 setMode(mode:Mode,reset=false){
  if(!this.active?.modes.includes(mode)){this.report('This navigation mode is disabled for this scene.',true);return;}
  if(mode===this.mode&&!reset){this.report('');this.refreshHud();return;}
  this.pointerMove.set(0,0,0);this.stopFlight();this.routes.cancel();this.cancelTeleport();this.jumpRequested=false;this.navigator?.takeControl();
  if(mode==='explore'){
   if(!this.world||!this.character||!this.body||!this.capsule){this.report('Walk requires a loaded collision mesh.',true);return;}
   const start=this.active.viewpoints.find(p=>p.id===this.active!.walkStart),fallback=start?this.content.localToWorld(v(start.position)):undefined;
   const eye=this.camera.getWorldPosition(new THREE.Vector3());let feet=nearbyWalkingFeet(this.world,reset&&fallback?fallback:eye,this.viewHeight,this.capsule);
   if(!feet&&fallback)feet=nearbyWalkingFeet(this.world,fallback,this.viewHeight,this.capsule);
   if(!feet){this.report('No valid walking position nearby or at the walking start.',true);return;}
   this.updateCrouch(false,true);this.placeFeet(new THREE.Vector3(feet.x,feet.y,feet.z));this.currentViewpoint='';this.onViewpoint('');
  }else if(mode==='fly'){
   const eye=this.camera.getWorldPosition(new THREE.Vector3());this.crouched=false;this.capsule?.setShape(new RAPIER.Capsule(.6,.25));this.velocityY=0;this.lastSafeHead=undefined;
   const destination=this.world?nearbyFlyPosition(this.world,eye,this.capsule):eye;if(destination)this.rig.position.add(new THREE.Vector3(destination.x-eye.x,destination.y-eye.y,destination.z-eye.z));this.navigator=undefined;this.currentViewpoint='';this.onViewpoint('');
  }else{this.updateCrouch(false,true);this.velocityY=0;this.lastSafeHead=undefined;}
  this.mode=mode;this.onMode(mode);this.report('');
  if(mode==='jumps'){const remembered=this.lastViewpoints.get(this.active.id),target=this.active.viewpoints.find(p=>p.id===remembered)||this.active.viewpoints.find(p=>p.id===this.active!.entry)||this.active.viewpoints[0];if(target)this.jump(target.id);}
  this.refreshHud();
 }
 private stopFlight(){if(!this.flight)return;this.flight=undefined;this.navigator=undefined;this.thumbnailPending=undefined;const eye=this.camera.getWorldPosition(new THREE.Vector3());if(this.body)this.body.setTranslation({x:eye.x,y:eye.y-.85,z:eye.z},true);}
 private placeFeet(point:THREE.Vector3){this.stopFlight();this.navigator=undefined;this.lastSafeHead=undefined;const xr=this.renderer.xr.isPresenting;const offset=xr?this.camera.getWorldPosition(new THREE.Vector3()).sub(this.rig.position):new THREE.Vector3();this.rig.position.set(point.x-(xr?offset.x:0),point.y+(xr?0:this.walkEyeHeight),point.z-(xr?offset.z:0));if(this.body){this.body.setTranslation({x:point.x,y:point.y+(this.crouched?.57:.87),z:point.z},true);this.world?.step();}this.velocityY=0;}
 jump(id:string,animate=true){const saved=this.active?.viewpoints.find(x=>x.id===id);if(!saved)return;this.navigator=new ViewNavigation(saved);const pose=this.navigator.pose();const p={...saved,...pose} as Viewpoint;this.thumbnailPending=this.editing?{id,after:performance.now()+1100}:undefined;this.updateCrouch(false,true);this.routes.cancel();this.cancelTeleport();const pt=this.content.localToWorld(v(p.position));const q=this.content.getWorldQuaternion(new THREE.Quaternion()).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(...p.rotation,'YXZ')));const e=new THREE.Euler().setFromQuaternion(q,'YXZ');const xr=this.renderer.xr.isPresenting,offset=xr?this.camera.getWorldPosition(new THREE.Vector3()).sub(this.rig.position):new THREE.Vector3();const to=pt.clone();if(xr){this.viewXROffset.copy(offset).applyQuaternion(this.rig.quaternion.clone().invert());this.viewXROffset.y=0;const anchor=this.viewXROffset.clone().applyAxisAngle(new THREE.Vector3(0,1,0),e.y);to.x-=anchor.x;to.z-=anchor.z;to.y-=1.7;}animate=animate&&(!xr||this.xrFly);if(xr&&!animate)this.fadeUntil=performance.now()+220;const toYaw=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),e.y);this.flight=animate?{start:performance.now(),duration:THREE.MathUtils.clamp(this.rig.position.distanceTo(to)*100,850,2600),from:this.rig.position.clone(),to,fromYaw:this.rig.quaternion.clone(),toYaw,pitch:this.camera.rotation.x,targetPitch:e.x}:undefined;if(!animate){this.rig.position.copy(to);this.rig.quaternion.copy(toYaw);if(!xr){this.camera.position.set(0,0,0);this.camera.rotation.set(e.x,0,0,'YXZ');}if(this.body)this.body.setTranslation({x:pt.x,y:pt.y-.85,z:pt.z},true);}this.currentViewpoint=id;if(this.active)this.lastViewpoints.set(this.active.id,id);this.onViewpoint(id);this.descriptionLabel&&releaseUI(this.descriptionLabel);this.descriptionLabel=p.description?panel(p.description.length>180?p.description.slice(0,160)+'… · Read more':p.description,1.8,.4):undefined;if(this.descriptionLabel){this.descriptionLabel.renderOrder=110;this.descriptionLabel.userData.action=()=>{this.currentPage={id:'view-description',title:p.name,html:'',blocks:[{type:'text',text:p.description||'',url:''}]};this.hudPage=0;this.menuOpen=true;this.refreshHud(true);};this.overlay.add(this.descriptionLabel);}if(!this.editing)this.audio.setViewpoint(p.audio,this.base);}

 private steerView(pose:{position:number[];rotation:number[]}){if(!this.flight){this.applyViewPose(pose);return;}const point=this.content.localToWorld(new THREE.Vector3(...pose.position)),q=this.content.getWorldQuaternion(new THREE.Quaternion()).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(pose.rotation[0],pose.rotation[1],pose.rotation[2],'YXZ'))),e=new THREE.Euler().setFromQuaternion(q,'YXZ');if(this.renderer.xr.isPresenting){const offset=this.viewXROffset.clone().applyAxisAngle(new THREE.Vector3(0,1,0),e.y);point.x-=offset.x;point.z-=offset.z;point.y-=1.7;}this.flight.to.copy(point);this.flight.toYaw.setFromAxisAngle(new THREE.Vector3(0,1,0),e.y);this.flight.targetPitch=e.x;}
 private applyViewPose(pose:{position:number[];rotation:number[]}){const position=this.content.localToWorld(new THREE.Vector3(...pose.position)),q=this.content.getWorldQuaternion(new THREE.Quaternion()).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(pose.rotation[0],pose.rotation[1],pose.rotation[2],'YXZ'))),e=new THREE.Euler().setFromQuaternion(q,'YXZ');if(this.renderer.xr.isPresenting){const offset=this.viewXROffset.clone().applyAxisAngle(new THREE.Vector3(0,1,0),e.y);this.rig.position.set(position.x-offset.x,position.y-1.7,position.z-offset.z);this.rig.rotation.set(0,e.y,0);}else{this.rig.position.copy(position);this.rig.rotation.set(0,e.y,0);this.camera.position.set(0,0,0);this.camera.rotation.set(e.x,0,0,'YXZ');}}
 get ready(){return !this.status&&!!this.mesh?.parent;}
 frameViewGeometry(){const view=this.viewGeometry.view;if(!view)return;this.stopFlight();this.navigator=undefined;this.thumbnailPending=undefined;const center=view.type==='orbit'&&view.orbit?view.orbit.center:view.type==='slider'&&view.slider?view.slider.origin:view.position;const size=view.orbit?.radius||Math.max(...view.slider?.bounds||[1,1]);const target=this.content.localToWorld(new THREE.Vector3(...center)),position=this.content.localToWorld(new THREE.Vector3(...center).add(new THREE.Vector3(.85,.6,1.5).multiplyScalar(size*1.5))),matrix=new THREE.Matrix4().lookAt(position,target,new THREE.Vector3(0,1,0)),e=new THREE.Euler().setFromRotationMatrix(matrix,'YXZ');this.rig.position.copy(position);this.rig.rotation.set(0,e.y,0);this.camera.position.set(0,0,0);this.camera.rotation.set(e.x,0,0,'YXZ');this.currentViewpoint='';this.onViewpoint('');}
 showViewGeometry(view?:Viewpoint){const selected=this.selected?.userData.geometryHandle;if(this.viewGeometry.rebuild(view)){if(this.selected?.userData.geometryHandle){this.gizmo.detach();this.selected=undefined;}if(selected){const handle=this.viewGeometry.handles().find(h=>h.name===selected);if(handle){this.selected=handle;this.gizmo.attach(handle);}}}this.viewGeometry.group.visible=!!view&&this.editing;}
 setGeometryTool(mode:'translate'|'rotate'){const plane=this.viewGeometry.handles().find(h=>h.name==='plane');if(plane){this.selected=plane;this.gizmo.attach(plane);}this.gizmo.setMode(mode);}
 private turnXR(angle:number){if(this.mode==='jumps'&&!this.editing&&this.navigator){this.navigator.takeControl();if(this.navigator.type==='slider')this.navigator.rotation[1]+=angle;else this.navigator.yaw+=angle;this.steerView(this.navigator.pose());return;}const head=this.camera.getWorldPosition(new THREE.Vector3());const offset=head.clone().sub(this.rig.position);const delta=offset.clone().sub(offset.clone().applyAxisAngle(new THREE.Vector3(0,1,0),angle));this.rig.position.add(delta);this.rig.rotation.y+=angle;if(this.body&&this.mode==='explore'){const p=this.body.translation();this.body.setTranslation({x:p.x+delta.x,y:p.y,z:p.z+delta.z},true);}}
 capture():Viewpoint{this.scene.updateMatrixWorld(true);const p=this.content.worldToLocal(this.camera.getWorldPosition(new THREE.Vector3()));const q=this.content.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(this.camera.getWorldQuaternion(new THREE.Quaternion()));const e=new THREE.Euler().setFromQuaternion(q,'YXZ');return {thumbnail:this.thumbnail(),id:crypto.randomUUID(),name:'New viewpoint',position:p.toArray() as Vec3,rotation:[e.x,e.y,e.z]};}
 thumbnail(){if(!this.renderer.xr.isPresenting){const helper=this.gizmo.getHelper(),geo=this.viewGeometry.group,states=[helper.visible,geo.visible,this.collider?.visible];helper.visible=false;geo.visible=false;if(this.collider)this.collider.visible=false;this.renderer.autoClear=true;this.renderer.render(this.scene,this.camera);helper.visible=states[0]!;geo.visible=states[1]!;if(this.collider)this.collider.visible=states[2]!;}const source=this.renderer.domElement,canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;const context=canvas.getContext('2d')!;const scale=Math.max(320/source.width,180/source.height);context.drawImage(source,(320-source.width*scale)/2,(180-source.height*scale)/2,source.width*scale,source.height*scale);return canvas.toDataURL('image/jpeg',.7);}
 pointInFront():Vec3{const p=this.camera.getWorldPosition(new THREE.Vector3()).add(this.camera.getWorldDirection(new THREE.Vector3()).multiplyScalar(3));return this.content.worldToLocal(p).toArray() as Vec3;}
 pickNext(){this.pendingPick=true;}
 selectHotspot(id:string){if(this.viewGeometry.group.visible&&this.selected?.userData.geometryHandle)return;this.selected=this.bubbles.children.find(c=>c.userData.id===id);if(this.selected&&this.editing)this.gizmo.attach(this.selected);else this.gizmo.detach();}
 rebuildHotspots(){if(!this.selected?.userData.geometryHandle)this.gizmo.detach();for(const o of [...this.bubbles.children])releaseUI(o);for(const h of this.active?.hotspots||[]){const o=badge(h.kind==='page'?'i':h.kind==='scene'?'picture':'camera',h.label);o.position.fromArray(h.position);o.userData={id:h.id,hotspot:h};this.bubbles.add(o);}this.rebuildMarkers();}
 rebuildMarkers(){for(const o of [...this.viewMarkers.children])releaseUI(o);this.viewMarkers.visible=false;}
 private pointerRay(e:PointerEvent){const b=this.renderer.domElement.getBoundingClientRect();this.ray.setFromCamera(new THREE.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),this.camera);}
 private controllerRay(controller:THREE.Object3D){this.ray.set(controller.getWorldPosition(new THREE.Vector3()),new THREE.Vector3(0,0,-1).applyQuaternion(controller.getWorldQuaternion(new THREE.Quaternion())));this.ray.far=30;}
 private hitUI(){this.overlay.updateMatrixWorld(true);if(this.hud.visible){const hit=this.ray.intersectObjects(this.hud.children,false).find(h=>h.object.visible);if(hit)return hit.object;}const objects=[...this.bubbles.children,...(this.viewMarkers.visible?this.viewMarkers.children:[]),...(this.wristMenu.visible?[this.wristMenu]:[]),...(this.descriptionLabel?.visible?[this.descriptionLabel]:[])];return this.ray.intersectObjects(objects,false).find(h=>h.object.visible)?.object;}
 private highlight(object?:THREE.Object3D){for(const child of this.hud.children)if(child instanceof THREE.Mesh&&child.userData.action)(child.material as THREE.MeshBasicMaterial).color.set(child===object?'#bfdaed':'#ffffff');if(this.hovered!==object){this.hovered=object;this.renderer.domElement.style.cursor=object?'pointer':this.mode==='explore'?'crosshair':'grab';}for(const root of [...this.bubbles.children,...this.viewMarkers.children,this.wristMenu])for(const c of root.children)if(c.userData.caption)c.visible=root===object||(this.editing&&root===this.selected);}
 private activate(object:THREE.Object3D){const data=object.userData;if(data.action){data.action();return;}if(data.viewpoint){this.jump(data.viewpoint);return;}const h=data.hotspot as Hotspot|undefined;if(!h)return;this.routes.cancel();if(this.editing){this.selectHotspot(h.id);this.onSelect(h.id);}else if(h.kind==='scene')void this.selectScene(h.target,h.viewpoint);else if(h.kind==='viewpoint')this.jump(h.target);else{const page=this.project?.pages.find(p=>p.id===h.target);if(page){const content={...page,title:h.label};this.currentPage=content;this.hudPage=0;if(this.renderer.xr.isPresenting){this.menuOpen=true;this.refreshHud(true);}else this.onPage(content);}}}
 private click(e:PointerEvent){this.pointerRay(e);if(this.editing&&this.viewGeometry.group.visible){const geometryHit=this.ray.intersectObjects(this.viewGeometry.handles(),false)[0];if(geometryHit){this.selected=geometryHit.object;this.gizmo.setMode('translate');this.gizmo.attach(this.selected);return;}}if(this.pendingPick){this.pendingPick=false;const hit=this.mesh?this.ray.intersectObject(this.mesh)[0]:undefined;this.onPick(hit?this.content.worldToLocal(hit.point).toArray() as Vec3:this.pointInFront());return;}const hit=this.hitUI();if(hit){this.activate(hit);return;}if(this.mode==='explore'&&!this.blocked&&!this.status){const ground=this.world?.castRayAndGetNormal(new RAPIER.Ray(this.ray.ray.origin,this.ray.ray.direction),100,true,undefined,undefined,this.capsule);const splatHit=!ground&&this.mesh?this.ray.intersectObject(this.mesh)[0]:undefined;let point=ground?this.ray.ray.at(ground.timeOfImpact,new THREE.Vector3()):splatHit?.point;if(point&&(!ground||ground.normal.y<Math.SQRT1_2)){const probe=point.clone();if(ground)probe.addScaledVector(new THREE.Vector3(ground.normal.x,0,ground.normal.z).normalize(),.4);probe.y+=.2;const floor=this.world?.castRayAndGetNormal(new RAPIER.Ray(probe,{x:0,y:-1,z:0}),6,true,undefined,undefined,this.capsule);point=floor&&floor.normal.y>=Math.SQRT1_2?probe.add(new THREE.Vector3(0,-floor.timeOfImpact,0)):undefined;}if(point)this.walkTo(point);}}
 walkTo(point:THREE.Vector3){if(this.mode!=='explore'||!this.body)return;const p=this.body.translation();this.routeStall=0;this.routes.find({x:p.x,y:p.y-(this.crouched?.55:.85),z:p.z},point);}
 private triggerStart(controller:THREE.XRTargetRaySpace){this.audio.unlock();this.navigator?.takeControl();this.controllerRay(controller);const hit=this.hitUI();this.held.set(controller,hit||null);if(!hit&&!this.status&&!this.blocked){this.teleportController=controller;this.updateTeleport();}}
 private triggerEnd(controller:THREE.XRTargetRaySpace){if(!this.held.has(controller))return;const pressed=this.held.get(controller);this.held.delete(controller);this.controllerRay(controller);if(pressed&&this.hitUI()===pressed){this.activate(pressed);}else if(!pressed&&this.teleportController===controller&&!this.status){this.updateTeleport();if(this.teleportPoint){this.routes.cancel();this.placeFeet(this.teleportPoint);this.currentViewpoint='';this.onViewpoint('');this.fadeUntil=performance.now()+220;}}this.cancelTeleport();}
 private updateTeleport(){if(!this.teleportController)return;this.controllerRay(this.teleportController);this.teleportPoint=undefined;this.teleportRing.visible=false;if(this.hitUI()||this.ray.ray.direction.y>-.06)return;const origin=this.ray.ray.origin,direction=this.ray.ray.direction;let point:THREE.Vector3|undefined,valid=true;
  if(this.mode==='explore'&&this.world){const hit=this.world.castRayAndGetNormal(new RAPIER.Ray(origin,direction),25,true,undefined,undefined,this.capsule);if(hit){point=this.ray.ray.at(hit.timeOfImpact,new THREE.Vector3());valid=hit.normal.y>=Math.SQRT1_2&&!this.world.intersectionWithShape({x:point.x,y:point.y+.87,z:point.z},{x:0,y:0,z:0,w:1},new RAPIER.Capsule(.58,.24),undefined,undefined,this.capsule);}}else if(this.mesh){const hit=this.ray.intersectObject(this.mesh)[0];if(hit&&hit.distance<25)point=hit.point;}
  if(point){this.teleportRing.visible=true;this.teleportRing.position.copy(point).add(new THREE.Vector3(0,.04,0));(this.teleportRing.material as THREE.MeshBasicMaterial).color.set(valid?0x9fffc8:0xff665e);if(valid)this.teleportPoint=point;}}
 private cancelTeleport(){this.teleportController=undefined;this.teleportPoint=undefined;this.teleportRing.visible=false;}
 async enterXR(){try{if(!navigator.xr||!await navigator.xr.isSessionSupported('immersive-vr'))throw new Error('WebXR immersive VR is unavailable in this browser.');const session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor']});await this.renderer.xr.setSession(session);}catch(e){this.report(String(e),true);}}
 private button(text:string,y:number,action:()=>void,width=1.65,x=0,bg='rgba(0,0,0,.18)'){const mesh=panel(text,width,.21,bg);mesh.position.set(x,y,.025);mesh.userData.action=action;this.hud.add(mesh);return mesh;}
 toggleMenu(){this.menuOpen=!this.menuOpen;this.currentPage=null;this.confirmExit=false;this.cancelTeleport();this.routes.cancel();this.refreshHud(true);}
 refreshHud(reposition=false){for(const c of [...this.hud.children])releaseUI(c);this.hud.visible=this.renderer.xr.isPresenting&&this.menuOpen;if(!this.hud.visible)return;
  if(reposition||this.menuAnchor.lengthSq()===0){const head=this.camera,position=head.getWorldPosition(new THREE.Vector3()),direction=head.getWorldDirection(new THREE.Vector3());direction.y=0;if(direction.lengthSq()<.01)direction.set(0,0,-1);direction.normalize();this.hud.position.copy(position).addScaledVector(direction,1.9);this.hud.position.y-=.12;this.hud.lookAt(position.x,this.hud.position.y,position.z);this.menuAnchor.copy(this.hud.position);}
  const background=panel('',1.95,2.2,'rgba(0,0,0,.16)');background.position.z=-.015;background.renderOrder=90;background.userData.blocks=true;this.hud.add(background);const title=panel(this.currentPage?.title||'TOUR MENU',1.55,.19);title.position.set(-.12,.93,.02);this.hud.add(title);this.button('×',.93,()=>{this.menuOpen=false;this.currentPage=null;this.refreshHud();},.22,.78);
  if(this.confirmExit){const text=panel(`Leave virtual reality?
Your tour will stay open in the browser.`,1.65,.65);text.position.y=.3;this.hud.add(text);this.button('Stay in VR',-.25,()=>{this.confirmExit=false;this.refreshHud();});this.button('Confirm: exit VR',-.55,()=>void this.renderer.xr.getSession()?.end(),1.65,0,'rgba(244,219,214,.94)');return;}
  if(this.currentPage){const page=this.currentPage,entries=textPages(page),block=entries[this.hudPage];const text=page.html?'This custom page is available in the browser view.':block?.type==='embed'?'This external embed is available in the browser view.':block?.type==='link'?block.text+'\n'+block.url+'\nAvailable in the browser view.':block?.text||'No content';const body=panel(text,1.65,1.12);body.position.y=.2;this.hud.add(body);if(block?.type==='image'){const index=this.hudPage;new THREE.TextureLoader().load(new URL(block.url,this.base).href,texture=>{if(this.currentPage!==page||this.hudPage!==index||!body.parent){texture.dispose();return;}texture.colorSpace=THREE.SRGBColorSpace;(body.material as THREE.MeshBasicMaterial).map?.dispose();(body.material as THREE.MeshBasicMaterial).map=texture;});}this.button('Previous',-.55,()=>{this.hudPage=Math.max(0,this.hudPage-1);this.refreshHud();},.78,-.43);this.button('Next',-.55,()=>{this.hudPage=Math.min(entries.length-1,this.hudPage+1);this.refreshHud();},.78,.43);this.button('Back to menu',-.84,()=>{this.currentPage=null;this.refreshHud();});return;}
  for(const [i,tab] of (['move','scenes','views','options'] as const).entries())this.button(tab==='move'?'Move':tab==='scenes'?'Scenes':tab==='views'?'Views':'Options',.64,()=>{this.menuTab=tab;this.menuPage=0;this.refreshHud();},.40,(i-1.5)*.44,this.menuTab===tab?'rgba(206,225,234,.96)':'rgba(245,248,250,.90)');
  if(this.status){const message=panel(this.status,1.65,.42,'rgba(249,234,204,.96)');message.position.y=.28;this.hud.add(message);this.button('Retry scene',-.06,()=>{if(this.active)void this.selectScene(this.active.id);});this.button('Choose another scene',-.34,()=>{this.menuTab='scenes';this.status='';this.refreshHud();});}
  else if(this.menuTab==='move'){const modes=this.active?.modes||[];const names={jumps:'Teleport & viewpoints',fly:'Free flight',explore:'Walk'};modes.forEach((mode,index)=>this.button((mode===this.mode?'✓ ':'')+names[mode],.3-index*.26,()=>{this.setMode(mode);this.menuOpen=false;this.refreshHud();}));const help=panel(`Hold trigger: aim teleport · release: move
Fly: left stick move; right stick lift / turn
Walk: left stick move; right stick turn
Grip: open or close this menu`,1.65,.55);help.position.y=-.58;this.hud.add(help);}
  else if(this.menuTab==='options'){this.button('Movement: '+(this.swapSticks?'right stick':'left stick'),.32,()=>{this.swapSticks=!this.swapSticks;this.refreshHud();});this.button('Turning: '+(this.snap?'30° snap':'smooth'),.07,()=>{this.snap=!this.snap;this.refreshHud();});this.button('Speed: '+this.speed+' m/s',-.18,()=>{const speeds=[.75,1.5,3,6];this.speed=speeds[(speeds.indexOf(this.speed)+1)%speeds.length];this.refreshHud();});this.button('View transitions: '+(this.xrFly?'fly':'fade'),-.43,()=>{this.xrFly=!this.xrFly;this.refreshHud();});this.button('Audio: '+(this.audio.muted?'muted':'on'),-.68,()=>{this.audio.setMuted(!this.audio.muted);this.refreshHud();});}
  else {const list=this.menuTab==='scenes'?this.project?.scenes||[]:this.active?.viewpoints||[],pages=Math.max(1,Math.ceil(list.length/4));this.menuPage=Math.min(this.menuPage,pages-1);list.slice(this.menuPage*4,this.menuPage*4+4).forEach((item,index)=>this.button((this.menuTab==='views'?String(this.menuPage*4+index+1)+'. ':'')+item.name,.3-index*.25,()=>{if(this.menuTab==='scenes')void this.selectScene(item.id);else this.jump(item.id);this.menuOpen=false;this.refreshHud();}));if(pages>1){this.button('Previous',-.74,()=>{this.menuPage=(this.menuPage+pages-1)%pages;this.refreshHud();},.78,-.43);this.button('Next',-.74,()=>{this.menuPage=(this.menuPage+1)%pages;this.refreshHud();},.78,.43);}}
  this.button('Exit VR…',-.98,()=>{this.confirmExit=true;this.refreshHud();},1.65,0,'rgba(244,229,226,.94)');
 }
 private frame(time:number){
  const dt=Math.min(.05,(time-this.last)/1000||.016);this.frameMs=this.frameMs*.9+Math.max(1,time-this.last)*.1;this.last=time;const xr=this.renderer.xr.isPresenting;this.rig.updateMatrixWorld(true);if(xr)this.renderer.xr.updateCamera(this.camera);const cam=this.camera;
  let x=this.touch.x,z=this.touch.y,y=this.touchLift,turn=0;
  if(!this.blocked&&!this.gizmo.dragging&&!(xr&&this.menuOpen)){
   x+=((this.keys.has('KeyD')||this.keys.has('ArrowRight'))?1:0)-((this.keys.has('KeyA')||this.keys.has('ArrowLeft'))?1:0);z+=((this.keys.has('KeyS')||this.keys.has('ArrowDown'))?1:0)-((this.keys.has('KeyW')||this.keys.has('ArrowUp'))?1:0);y+=(this.keys.has('KeyE')?1:0)-(this.keys.has('KeyQ')?1:0);
   if(xr){const motion=xrMotion(this.renderer.xr.getSession()?.inputSources||[],this.mode,this.swapSticks);x+=motion.strafe;z+=motion.forward;y+=motion.lift;turn=motion.turn;if(this.snap){if(Math.abs(turn)>.6&&this.turnReady){this.turnXR(-Math.sign(turn)*Math.PI/6);this.turnReady=false;}if(Math.abs(turn)<.2)this.turnReady=true;}else this.turnXR(-turn*dt*1.5);}
   if(this.mode==='jumps'&&!this.editing&&this.navigator){if(Math.abs(x)+Math.abs(z)+Math.abs(y)>.01)this.steerView(this.navigator.drag((this.navigator.type==='photosphere'?x:-x)*dt*180,-(z-y)*dt*180));else if(!this.currentPage&&!this.flight){const pose=this.navigator.animate(dt);if(pose)this.applyViewPose(pose);}}
   const manual=Math.abs(x)+Math.abs(z)+Math.abs(y)>.01||this.pointerMove.lengthSq()>0;if(manual){this.routes.cancel();if(!(this.mode==='jumps'&&!this.editing&&this.navigator))this.stopFlight();this.navigator?.takeControl();}
   if((this.mode!=='jumps'||this.editing)&&!this.status&&!this.flight){
    if(this.mode==='explore')this.updateCrouch(this.touchCrouch||this.keys.has('ShiftLeft')||this.keys.has('ShiftRight'));
    const orientation=cam.getWorldQuaternion(new THREE.Quaternion());
    const forward=new THREE.Vector3(0,0,-1).applyQuaternion(orientation),right=new THREE.Vector3(1,0,0).applyQuaternion(orientation);
    // Walking and headset locomotion stay level; desktop flight follows the view.
    if(this.mode==='explore'||xr){forward.y=0;right.y=0;forward.normalize();right.normalize();}
    const move=right.multiplyScalar(x).addScaledVector(forward,-z).add(new THREE.Vector3(0,y,0));if(move.length()>1)move.normalize();move.multiplyScalar(this.speed*dt*(this.mode==='explore'?(this.crouched?.55:1):((this.keys.has('ShiftLeft')||this.keys.has('ShiftRight'))?2:1))).add(this.pointerMove);
    if(this.mode==='explore'&&!manual&&this.body){const p=this.body.translation(),toward=this.routes.direction(p);if(toward){const distance=toward.length();move.copy(toward.normalize().multiplyScalar(Math.min(distance,this.speed*dt)));}}
    if((manual||move.lengthSq()>.000001)&&this.currentViewpoint){this.currentViewpoint='';this.onViewpoint('');}
    if(this.mode!=='explore'){const delta=this.world&&this.mode==='fly'?flyMovement(this.world,cam.getWorldPosition(new THREE.Vector3()),move,this.capsule):move;this.rig.position.add(new THREE.Vector3(delta.x,delta.y,delta.z));}
    else if(this.world&&this.character&&this.capsule&&this.body){if(this.jumpRequested&&this.character.computedGrounded()){this.velocityY=4.8;this.character.disableSnapToGround();}this.jumpRequested=false;if(this.velocityY<=0)this.character.enableSnapToGround(.3);this.velocityY=Math.max(-15,this.velocityY-9.81*dt);move.y=this.velocityY*dt;const d=characterMovement(this.world,this.character,this.capsule,this.body,move),old=this.body.translation();this.body.setNextKinematicTranslation({x:old.x+d.x,y:old.y+d.y,z:old.z+d.z});this.world.timestep=dt;this.world.step();if(this.character.computedGrounded())this.velocityY=0;const next=this.body.translation();this.rig.position.add(new THREE.Vector3(next.x-old.x,next.y-old.y,next.z-old.z));if(this.routes.points.length&&Math.hypot(move.x,move.z)>.001&&Math.hypot(next.x-old.x,next.z-old.z)<.0005)this.routeStall+=dt;else this.routeStall=0;if(this.routeStall>2){this.routes.cancel();}if(next.y<-200&&this.active)this.setMode('explore',true);}
   }
  }
  this.pointerMove.set(0,0,0);
  if(this.flight&&!this.blocked){const f=this.flight,t=THREE.MathUtils.clamp((time-f.start)/f.duration,0,1),ease=t*t*(3-2*t);this.rig.position.lerpVectors(f.from,f.to,ease);this.rig.quaternion.slerpQuaternions(f.fromYaw,f.toYaw,ease);if(!xr)this.camera.rotation.x=THREE.MathUtils.lerp(f.pitch,f.targetPitch,ease);if(t===1){this.flight=undefined;const eye=this.camera.getWorldPosition(new THREE.Vector3());if(this.body)this.body.setTranslation({x:eye.x,y:eye.y-.85,z:eye.z},true);}}
  this.scene.updateMatrixWorld(true);const cameraPosition=cam.getWorldPosition(new THREE.Vector3()),cameraRotation=cam.getWorldQuaternion(new THREE.Quaternion());
  if(xr&&this.menuRecenterFrames>0&&--this.menuRecenterFrames===0)this.refreshHud(true);
  if(this.editing&&this.viewGeometry.group.visible)for(const handle of this.viewGeometry.handles()){const distance=handle.getWorldPosition(new THREE.Vector3()).distanceTo(cameraPosition);handle.scale.setScalar(Math.max(.6,distance*.12)/(this.active?.transform.scale||1));}
  this.viewMarkers.visible=false;
  for(const group of [this.bubbles,this.viewMarkers])for(const marker of group.children){marker.lookAt(cameraPosition);const distance=marker.getWorldPosition(new THREE.Vector3()).distanceTo(cameraPosition);marker.scale.setScalar(THREE.MathUtils.clamp(distance*.065,.38,1.4)*(marker===this.hovered?1.15:1)/(this.active?.transform.scale||1));for(const c of marker.children)if(c.userData.caption){const parentScale=marker.scale.x*(this.active?.transform.scale||1);const height=xr?distance*.07:2*Math.tan(THREE.MathUtils.degToRad(this.camera.fov)/2)*distance*46/Math.max(1,this.host.clientHeight);c.scale.setScalar(height/(.16*parentScale));c.position.y=-.2-.08*c.scale.y;}}
  if(xr){const hand=this.controllers.find(c=>c.userData.handedness==='left')||this.controllers[0];this.wristMenu.visible=!!hand?.visible;if(hand){this.wristMenu.position.copy(hand.getWorldPosition(new THREE.Vector3())).add(new THREE.Vector3(-.08,.08,-.1).applyQuaternion(hand.getWorldQuaternion(new THREE.Quaternion())));this.wristMenu.lookAt(cameraPosition);this.wristMenu.scale.setScalar(.32);}let hover:THREE.Object3D|undefined;for(const controller of this.controllers){const line=controller.userData.rayLine as THREE.Line;line.visible=controller.visible;line.position.copy(controller.getWorldPosition(new THREE.Vector3()));line.quaternion.copy(controller.getWorldQuaternion(new THREE.Quaternion()));this.controllerRay(controller);const target=this.hitUI();const hit=target?this.ray.intersectObject(target,false)[0]:undefined;const tip=controller.userData.tip as THREE.Mesh;tip.visible=controller.visible&&!!hit;if(hit){tip.position.copy(hit.point);tip.scale.setScalar(Math.max(.6,hit.distance*.45));}const length=hit?.distance||3;line.scale.z=length/12;(line.material as THREE.LineBasicMaterial).color.set(target?.userData.action||target?.userData.hotspot?'#80b7d4':'#bdcbd1');hover=target||hover;}this.highlight(hover);if(this.teleportController&&time-this.aimTime>60){this.aimTime=time;this.updateTeleport();}}
  else{this.wristMenu.visible=false;for(const controller of this.controllers){(controller.userData.rayLine as THREE.Line).visible=false;(controller.userData.tip as THREE.Mesh).visible=false;}}
  if(this.descriptionLabel){this.descriptionLabel.visible=xr&&!!this.currentViewpoint&&!this.menuOpen;this.descriptionLabel.position.copy(cameraPosition).add(new THREE.Vector3(0,-.65,-2).applyQuaternion(cameraRotation));this.descriptionLabel.quaternion.copy(cameraRotation);}
  let opacity=time<this.fadeUntil?.95:0;
  if(xr&&(this.mode==='explore'||this.mode==='fly')&&this.world&&this.capsule){const inside=!!this.world.intersectionWithShape(cameraPosition,{x:0,y:0,z:0,w:1},new RAPIER.Ball(.1),undefined,undefined,this.capsule);const delta=this.lastSafeHead?cameraPosition.clone().sub(this.lastSafeHead):undefined;const crossed=delta&&delta.length()>.001?this.world.castRay(new RAPIER.Ray(this.lastSafeHead!,delta.clone().normalize()),delta.length(),true,undefined,undefined,this.capsule):null;if(inside||crossed)opacity=.95;else this.lastSafeHead=cameraPosition.clone();}
  this.fade.position.copy(cameraPosition).add(cam.getWorldDirection(new THREE.Vector3()).multiplyScalar(.2));this.fade.quaternion.copy(cameraRotation);(this.fade.material as THREE.MeshBasicMaterial).opacity=opacity;this.fade.visible=opacity>0;
  this.renderer.autoClear=true;this.renderer.render(this.scene,this.camera);this.renderer.autoClear=false;this.renderer.clearDepth();this.renderer.render(this.overlay,this.camera);this.renderer.autoClear=true;
  if(this.thumbnailPending&&!this.flight&&time>this.thumbnailPending.after&&this.editing&&this.currentViewpoint===this.thumbnailPending.id){if((this.spark as any).display?.numSplats>0){const id=this.thumbnailPending.id;this.thumbnailPending=undefined;this.onViewpointThumbnail(id,this.thumbnail());}}
 }
 dispose(){this.viewGeometry.clear();this.dead=true;++this.generation;this.renderer.setAnimationLoop(null);this.clearScene();this.routes.dispose();for(const child of [...this.overlay.children])releaseUI(child);this.gizmo.dispose();this.observers.disconnect();this.cleanup.forEach(f=>f());for(const c of [...this.hud.children])release(c);this.spark.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
