import {bubbleIcons} from './bubble-icons';
import * as THREE from 'three';
export function releaseUI(object:THREE.Object3D){object.traverse(c=>{if(c instanceof THREE.Mesh||c instanceof THREE.Line){c.geometry.dispose();for(const m of Array.isArray(c.material)?c.material:[c.material]){(m as THREE.MeshBasicMaterial).map?.dispose();m.dispose();}}});object.removeFromParent();}
export function textTexture(text:string,width=768,height=128,bg='rgba(0,0,0,.18)',font=34){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const c=canvas.getContext('2d')!;c.fillStyle=bg;c.beginPath();c.roundRect(0,0,width,height,Math.min(26,height/5));c.fill();c.fillStyle='#f5f5f5';c.shadowColor='rgba(0,0,0,.85)';c.shadowBlur=4;c.font=`600 ${font}px system-ui`;c.textBaseline='top';let y=24;for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(c.measureText(line+word).width>width-48){c.fillText(line,24,y);line='';y+=font*1.35;}line+=word+' ';}c.fillText(line,24,y);y+=font*1.35;}const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
export function bubbleTexture(symbol:string,active=false,tone:'content'|'viewpoint'='content',glassOpacity=.16){const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const c=canvas.getContext('2d')!;const gradient=c.createLinearGradient(0,0,150,256);gradient.addColorStop(0,`rgba(0,0,0,${glassOpacity})`);gradient.addColorStop(1,`rgba(0,0,0,${glassOpacity*.375})`);c.fillStyle=gradient;c.beginPath();c.arc(128,128,117,0,Math.PI*2);c.fill();c.lineWidth=active?7:3;c.strokeStyle=active?'#678da3':'rgba(255,255,255,.6)';c.stroke();c.fillStyle='#f5f5f5';c.shadowColor='rgba(0,0,0,.7)';c.shadowBlur=3;const path=bubbleIcons[symbol];if(path){c.save();c.translate(66,66);c.scale(124/960,124/960);c.translate(0,960);c.fill(new Path2D(path));c.restore();}else{c.font='500 100px system-ui';c.textAlign='center';c.textBaseline='middle';c.fillText(symbol,128,135);}const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
// Separate glass from its icon/border so distance fading never hides the action.
export function bubbleGlass(glassOpacity:number){const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const c=canvas.getContext('2d')!;const g=c.createLinearGradient(0,0,150,256);g.addColorStop(0,`rgba(0,0,0,${glassOpacity})`);g.addColorStop(1,`rgba(0,0,0,${glassOpacity*.375})`);c.fillStyle=g;c.beginPath();c.arc(128,128,117,0,Math.PI*2);c.fill();const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;return t;}
export function badge(symbol:string,title:string,active=false,tone:'content'|'viewpoint'='content',glassOpacity?:number){const root=new THREE.Mesh(new THREE.CircleGeometry(.16,48),new THREE.MeshBasicMaterial({map:bubbleTexture(symbol,active,tone,glassOpacity===undefined?.16:0),side:THREE.FrontSide,transparent:true,depthTest:false,depthWrite:false,toneMapped:false}));root.renderOrder=20;if(glassOpacity!==undefined){const glass=new THREE.Mesh(new THREE.CircleGeometry(.16,48),new THREE.MeshBasicMaterial({map:bubbleGlass(glassOpacity),transparent:true,depthTest:false,depthWrite:false,toneMapped:false,side:THREE.FrontSide}));glass.renderOrder=19;glass.userData.glass=true;root.add(glass);}const caption=new THREE.Mesh(new THREE.PlaneGeometry(1.1,.16),new THREE.MeshBasicMaterial({map:textTexture(title,768,112),transparent:true,depthTest:false,depthWrite:false,toneMapped:false,side:THREE.FrontSide}));caption.position.set(0,-.26,.01);caption.visible=false;caption.renderOrder=21;caption.userData.caption=true;root.add(caption);return root;}
export function panel(text:string,width:number,height:number,bg='rgba(0,0,0,.18)'){const mesh=new THREE.Mesh(new THREE.PlaneGeometry(width,height),new THREE.MeshBasicMaterial({map:textTexture(text,768,Math.max(100,Math.round(768*height/width)),bg,Math.round(34*1.65/width)),side:THREE.FrontSide,transparent:true,depthTest:false,depthWrite:false,toneMapped:false}));mesh.renderOrder=100;return mesh;}
