import React,{useState,useEffect,useRef} from 'react';import {createRoot} from 'react-dom/client';
import {TourRuntime} from './runtime';import type {Project,Hosting,TourScene,Mode,Page,Snapshot,Transform,Vec3} from './model';import {uid,emptyTransform} from './model';
import {blankProject,newScene,validateProject,renderPage,ProjectSchema,HostingSchema} from '../shared/project.mjs';
import './style.css';

export function Button({children,onClick,primary=false,disabled=false,title}:React.PropsWithChildren<{onClick:()=>void;primary?:boolean;disabled?:boolean;title?:string}>){return <button title={title} className={primary?'primary':''} onClick={onClick} disabled={disabled}>{children}</button>;}
export function Field({label,children}:React.PropsWithChildren<{label:string}>){return <label className="field"><span>{label}</span>{children}</label>;}
export function Vector({label,value,onChange}: {label:string;value:Vec3;onChange:(v:Vec3)=>void}){return <Field label={label}><div className="vector">{value.map((n,i)=><label key={i}><small>{'XYZ'[i]}</small><input aria-label={`${label} ${'XYZ'[i]}`} type="number" step="0.1" value={n} onChange={e=>{const next=[...value] as Vec3;next[i]=Number(e.target.value);onChange(next);}}/></label>)}</div></Field>;}
export function TransformForm({value,onChange}: {value:Transform;onChange:(v:Transform)=>void}){return <><Vector label="Position · meters" value={value.position} onChange={position=>onChange({...value,position})}/><Vector label="Rotation · degrees" value={value.rotation.map(x=>Math.round(x*180/Math.PI*100)/100) as Vec3} onChange={r=>onChange({...value,rotation:r.map(x=>x*Math.PI/180) as Vec3})}/><Field label="Uniform scale"><input type="number" min="0.0001" step="0.1" value={value.scale} onChange={e=>onChange({...value,scale:Math.max(.0001,Number(e.target.value))})}/></Field></>;}
export function Stage({onReady}:{onReady:(r:TourRuntime)=>void}){const host=useRef<HTMLDivElement>(null);const [error,setError]=useState('');useEffect(()=>{let r:TourRuntime;try{r=new TourRuntime(host.current!);onReady(r);}catch(e){setError(String(e));}return()=>r?.dispose();},[]);return <div className="stage" ref={host}>{error&&<div className="stage-error">WebGL2 could not start.<br/>{error}</div>}</div>;}
export function ControlsHelp(){return <div className="help-grid"><div><kbd>Mouse</kbd> Click the scene to capture · move to look</div><div><kbd>Escape</kbd> Release cursor · stop walking</div><div><kbd>Left drag</kbd> Look around in viewpoints / editor</div><div><kbd>Right drag</kbd> Pan</div><div><kbd>Scroll</kbd> Move forward / back</div><div><kbd>W A S D / arrows</kbd> Move</div><div><kbd>Q / E</kbd> Fly down / up</div><div><kbd>Shift</kbd> Walk: crouch · Fly: faster</div><div><kbd>Space</kbd> Walk: jump</div><div><kbd>Touch</kbd> Drag to look · pad to move</div><div><kbd>Walk</kbd> Click a destination · Escape stops</div><div><kbd>VR trigger</kbd> Hold to aim · release to teleport</div><div><kbd>VR grip</kbd> Open / close tour menu</div><div><kbd>Drone</kbd> Left stick: move · right: lift / turn</div></div>;}
export function useMobileControls(){const [choice,setChoice]=useState(()=>{try{return localStorage.getItem('spark-mobile-controls')||'auto';}catch{return 'auto';}}),[detected,setDetected]=useState(()=>matchMedia('(any-pointer: coarse)').matches||navigator.maxTouchPoints>0);useEffect(()=>{const query=matchMedia('(any-pointer: coarse)'),update=()=>setDetected(query.matches||navigator.maxTouchPoints>0);query.addEventListener('change',update);return()=>query.removeEventListener('change',update);},[]);return {choice,enabled:choice==='on'||choice==='auto'&&detected,setChoice:(value:string)=>{setChoice(value);try{localStorage.setItem('spark-mobile-controls',value);}catch{}}};}
export function MobileControlSetting({value,onChange}:{value:string;onChange:(value:string)=>void}){return <Field label="Mobile controls"><select aria-label="Mobile controls" value={value} onChange={e=>onChange(e.target.value)}><option value="auto">Automatic</option><option value="on">Always show</option><option value="off">Hide</option></select></Field>;}
function TouchAction({label,down,up}:{label:string;down:()=>void;up:()=>void}){return <button aria-label={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);down();}} onPointerUp={up} onPointerCancel={up} onLostPointerCapture={up}>{label}</button>;}
export function TouchPad({runtime,enabled,mode}:{runtime:TourRuntime|null;enabled?:boolean;mode?:Mode}){const active=useRef(false);const navigation=mode||runtime?.mode;const automatic=useMobileControls();const visible=enabled??automatic.enabled;useEffect(()=>()=>{runtime?.setTouch(0,0);runtime?.setTouchLift(0);runtime?.setTouchCrouch(false);},[runtime,visible,navigation]);if(!visible||navigation==='jumps')return null;const stop=()=>{active.current=false;runtime?.setTouch(0,0);};const move=(e:React.PointerEvent<HTMLDivElement>)=>{const b=e.currentTarget.getBoundingClientRect();runtime?.setTouch((e.clientX-b.left-b.width/2)/(b.width/2),(e.clientY-b.top-b.height/2)/(b.height/2));};return <div className="mobile-controls"><div className="touch-pad" aria-label="Touch movement pad" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);active.current=true;move(e);}} onPointerMove={e=>{if(active.current)move(e);}} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop}>↕<br/>↔</div><div className="touch-actions">{navigation==='explore'?<><TouchAction label="Crouch" down={()=>runtime?.setTouchCrouch(true)} up={()=>runtime?.setTouchCrouch(false)}/><TouchAction label="Jump" down={()=>runtime?.requestJump()} up={()=>{}}/></>:<><TouchAction label="Fly up" down={()=>runtime?.setTouchLift(1)} up={()=>runtime?.setTouchLift(0)}/><TouchAction label="Fly down" down={()=>runtime?.setTouchLift(-1)} up={()=>runtime?.setTouchLift(0)}/></>}</div></div>;}
function contentUrl(value:string,base:string){try{const url=new URL(value,base);return ['http:','https:'].includes(url.protocol)?url.href:'';}catch{return '';}}
export function ContentModal({page,base,onClose,runtime}:{page:Page;base:string;onClose:()=>void;runtime:TourRuntime|null}){
 const frame=useRef<HTMLIFrameElement>(null);
 useEffect(()=>{if(runtime)runtime.blocked=true;const listen=(e:MessageEvent)=>{if(e.source!==frame.current?.contentWindow)return;const data=e.data;if(!data||data.type!=='spark-tour-action')return;if(data.action==='close')onClose();else if(data.action==='scene'&&runtime?.project?.scenes.some(s=>s.id===data.sceneId)){void runtime.selectScene(data.sceneId,data.viewpointId);onClose();}else if(data.action==='viewpoint'&&runtime?.active?.viewpoints.some(v=>v.id===data.viewpointId)){runtime.jump(data.viewpointId);onClose();}};window.addEventListener('message',listen);return()=>{window.removeEventListener('message',listen);if(runtime)runtime.blocked=false;};},[page,runtime]);
 return <div className="modal-shade"><section className="content-modal" role="dialog" aria-modal="true" aria-label={page.title}><header><h2>{page.title}</h2><Button onClick={onClose}>Close ×</Button></header>{page.html?<iframe className="custom-content-frame" ref={frame} title={page.title} sandbox="allow-scripts allow-forms allow-popups" src={contentUrl(page.html,base)}/>:<div className="content-body">{page.blocks.map((block,index)=>block.type==='text'?<p key={index}>{block.text}</p>:block.type==='image'?<figure key={index}>{block.url&&<img src={contentUrl(block.url,base)} alt={block.text}/>}{block.text&&<figcaption>{block.text}</figcaption>}</figure>:block.type==='link'?<p key={index}><a href={contentUrl(block.url,base)} target="_blank" rel="noopener noreferrer">{block.text||block.url}</a></p>:<iframe key={index} className="content-embed" title={block.text||'Embedded content'} src={contentUrl(block.url,base)} sandbox="allow-scripts allow-same-origin allow-forms allow-popups" allow="fullscreen"/>)}</div>}</section></div>;
}
