import * as THREE from 'three';
import type {Viewpoint,Vec3} from './model';
export class ViewGeometry {
 readonly group=new THREE.Group();view?:Viewpoint;signature='';
 constructor(){this.group.name='viewpoint-geometry';}
 clear(){for(const child of [...this.group.children]){child.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){o.geometry.dispose();(o.material as THREE.Material).dispose();}});child.removeFromParent();}this.signature='';this.view=undefined;}
 rebuild(view?:Viewpoint){const signature=JSON.stringify(view&&[view.id,view.type,view.position,view.rotation,view.orbit,view.slider]);if(signature===this.signature)return false;this.clear();this.signature=signature||'';this.view=view?structuredClone(view):undefined;if(!view)return true;
 const line=(points:THREE.Vector3[],color=0xc4a473)=>{const o=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color,transparent:true,opacity:.7,depthTest:false}));o.renderOrder=499;this.group.add(o);return o;};
 const handle=(name:string,position:number[],color=0xd9b67a)=>{const o=new THREE.Mesh(new THREE.SphereGeometry(.085,16,12),new THREE.MeshBasicMaterial({color,depthTest:false}));o.name=name;o.position.fromArray(position);o.renderOrder=500;o.userData.geometryHandle=name;this.group.add(o);return o;};
 if(view.type==='orbit'&&view.orbit){const {center,radius,azimuthBounds,elevationBounds}=view.orbit,c=new THREE.Vector3(...center);handle('center',center);handle('radius',c.clone().add(new THREE.Vector3(radius,0,0)).toArray(),0x8dbfc9);const circle=Array.from({length:97},(_,i)=>c.clone().add(new THREE.Vector3(Math.sin(i/96*Math.PI*2)*radius,0,Math.cos(i/96*Math.PI*2)*radius)));line(circle);const point=(a:number,e=0)=>c.clone().add(new THREE.Vector3(Math.sin(a)*Math.cos(e),Math.sin(e),Math.cos(a)*Math.cos(e)).multiplyScalar(radius));if(azimuthBounds)azimuthBounds.forEach((a,i)=>{const p=point(THREE.MathUtils.degToRad(a));handle('azimuth'+i,p.toArray(),0xe0bd94);line([c,p]);});if(elevationBounds)elevationBounds.forEach((e,i)=>{const p=point(0,THREE.MathUtils.degToRad(e));handle('elevation'+i,p.toArray(),0x9dcfae);line([c,p]);});line(Array.from({length:65},(_,i)=>point(0,(i/64-.5)*Math.PI)),0x8dbfc9);
 }else if(view.type==='slider'&&view.slider){const s=view.slider,q=new THREE.Quaternion().setFromEuler(new THREE.Euler(...s.rotation,'YXZ')),origin=new THREE.Vector3(...s.origin),[width,height]=s.bounds||[4,2],point=(x:number,y:number)=>new THREE.Vector3(x,y,0).applyQuaternion(q).add(origin);const o=handle('plane',s.origin);o.quaternion.copy(q);line([point(-width/2,-height/2),point(width/2,-height/2),point(width/2,height/2),point(-width/2,height/2),point(-width/2,-height/2)]);line([point(-width/2,0),point(width/2,0)],0x8dbfc9);line([point(0,-height/2),point(0,height/2)],0x8dbfc9);if(s.bounds)handle('size',point(width/2,height/2).toArray(),0x8dbfc9);
 }else{handle('position',view.position);const center=new THREE.Vector3(...view.position);for(const axis of ['x','y'] as const)line(Array.from({length:49},(_,i)=>{const p=new THREE.Vector3(Math.cos(i/48*Math.PI*2)*.4,0,Math.sin(i/48*Math.PI*2)*.4);if(axis==='x')p.applyAxisAngle(new THREE.Vector3(1,0,0),Math.PI/2);return p.add(center);}));}
 return true;}
 handles(){return this.group.children.filter(o=>o.userData.geometryHandle);}
 patch(object:THREE.Object3D):Partial<Viewpoint>{const v=this.view!;const kind=object.userData.geometryHandle;const p=object.position;if(kind==='position')return {position:p.toArray() as Vec3};if(v.type==='orbit'&&v.orbit){const o=structuredClone(v.orbit),center=new THREE.Vector3(...o.center),delta=p.clone().sub(center);if(kind==='center'){const shift=p.clone().sub(center);o.center=p.toArray() as Vec3;return {orbit:o,position:new THREE.Vector3(...v.position).add(shift).toArray() as Vec3};}if(kind==='radius')o.radius=Math.max(.05,delta.length());if(kind.startsWith('azimuth')){const i=Number(kind.at(-1)),other=o.azimuthBounds![1-i];let angle=THREE.MathUtils.radToDeg(Math.atan2(delta.x,delta.z));angle+=Math.round((o.azimuthBounds![i]-angle)/360)*360;o.azimuthBounds![i]=i===0?Math.min(angle,other-.1):Math.max(angle,other+.1);}if(kind.startsWith('elevation')){const i=Number(kind.at(-1)),other=o.elevationBounds![1-i],angle=THREE.MathUtils.clamp(THREE.MathUtils.radToDeg(Math.asin(delta.y/Math.max(delta.length(),.001))),-89,89);o.elevationBounds![i]=i===0?Math.min(angle,other-.1):Math.max(angle,other+.1);}return {orbit:o};}if(v.type==='slider'&&v.slider){const s=structuredClone(v.slider);if(kind==='plane'){const shift=p.clone().sub(new THREE.Vector3(...s.origin));s.origin=p.toArray() as Vec3;const e=new THREE.Euler().setFromQuaternion(object.quaternion,'YXZ');s.rotation=[e.x,e.y,e.z];return {slider:s,position:new THREE.Vector3(...v.position).add(shift).toArray() as Vec3};}const delta=p.clone().sub(new THREE.Vector3(...s.origin)).applyQuaternion(new THREE.Quaternion().setFromEuler(new THREE.Euler(...s.rotation,'YXZ')).invert());s.bounds=[Math.max(.05,Math.abs(delta.x)*2),Math.max(.05,Math.abs(delta.y)*2)];return {slider:s};}return {};}
}
