import * as THREE from 'three';
type Point={x:number;y:number;z:number};
export class WalkingRoutes {
 private worker?:Worker;private pending?:{start:Point;end:Point};private request=0;private navigating=false;private lookDistance=0;followView=true;ready=false;error='';points:THREE.Vector3[]=[];line?:THREE.Mesh;onNotice=(text:string)=>{};
 constructor(private overlay:THREE.Scene){}
 build(parts:{positions:Float32Array;indices:Uint32Array}[]){this.dispose();this.error='';let vertices=0,indexCount=0;for(const p of parts){vertices+=p.positions.length;indexCount+=p.indices.length;}const positions=new Float32Array(vertices),indices=new Uint32Array(indexCount);let v=0,i=0;for(const p of parts){positions.set(p.positions,v);for(const index of p.indices)indices[i++]=index+v/3;v+=p.positions.length;}
  this.worker=new Worker(new URL('./navigation.worker.ts',import.meta.url),{type:'module'});this.worker.onmessage=e=>{const m=e.data;if(m.type==='ready'){this.ready=true;if(this.pending){const pending=this.pending;this.pending=undefined;this.send(pending.start,pending.end);}}else if(m.type==='path'&&m.id===this.request){this.points=m.path.map((p:Point)=>new THREE.Vector3(p.x,p.y,p.z));this.navigating=this.points.length>0;this.draw();}else if(m.type==='error'&&(m.id===undefined||m.id===this.request)){if(m.id===undefined)this.error=m.error;}};this.worker.onerror=()=>{this.error='Click-to-walk could not start. Manual walking is still available.';};this.worker.postMessage({type:'build',positions,indices},[positions.buffer,indices.buffer]);
 }
 find(start:Point,end:Point){this.cancel();if(!this.worker)return;this.navigating=true;if(!this.ready){this.pending={start:{...start},end:{...end}};return;}this.send(start,end);}
 // Tiny pointer jitter should not stop route steering. Deliberate looking takes
 // over for this walk, including input while the route is still being computed.
 look(dx:number,dy:number){if(!this.navigating&&!this.points.length&&!this.pending)return;this.lookDistance+=Math.hypot(dx,dy);if(this.lookDistance>=12)this.followView=false;}
 private send(start:Point,end:Point){this.worker!.postMessage({type:'path',id:this.request,start,end});}
 cancel(){this.pending=undefined;this.navigating=false;this.lookDistance=0;this.followView=true;++this.request;this.points=[];if(this.line){this.line.removeFromParent();this.line.geometry.dispose();(this.line.material as THREE.Material).dispose();this.line=undefined;}}
 private draw(){if(this.line){this.line.removeFromParent();this.line.geometry.dispose();(this.line.material as THREE.Material).dispose();this.line=undefined;}if(this.points.length<2)return;const curve=new THREE.CatmullRomCurve3(this.points,false,'centripetal');const samples=curve.getPoints(Math.max(16,Math.min(2048,Math.ceil(curve.getLength()*12)))),vertices:number[]=[],indices:number[]=[];for(let i=0;i<samples.length;i++){const before=samples[Math.max(0,i-1)],after=samples[Math.min(samples.length-1,i+1)],side=new THREE.Vector3(after.z-before.z,0,before.x-after.x).normalize().multiplyScalar(.23);for(const sign of [-1,1])vertices.push(samples[i].x+side.x*sign,samples[i].y+.045,samples[i].z+side.z*sign);if(i){const k=i*2;indices.push(k-2,k-1,k,k-1,k+1,k);}}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);this.line=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.28,side:THREE.DoubleSide,depthTest:false,depthWrite:false}));this.line.name='walking-path';this.line.renderOrder=10;this.overlay.add(this.line);}
 direction(position:Point){while(this.points.length&&Math.hypot(this.points[0].x-position.x,this.points[0].z-position.z)<.15)this.points.shift();if(!this.points.length){if(this.line){this.cancel();}return null;}return this.points[0].clone().sub(new THREE.Vector3(position.x,this.points[0].y,position.z));}
 dispose(){this.worker?.terminate();this.worker=undefined;this.ready=false;this.cancel();}
}
