const fs=require('node:fs/promises');const path=require('node:path');const {Readable}=require('node:stream');const {pipeline}=require('node:stream/promises');const {contained}=require('./server.cjs');
const remote=s=>/^https?:\/\//i.test(s);
async function exists(p){try{await fs.access(p);return true;}catch{return false;}}
function sourcePath(ref,root,sources){for(const [prefix,info] of Object.entries(sources)){if(ref.startsWith(prefix+'/'))return path.join(info.dir,ref.slice(prefix.length+1));}return path.join(root,ref);}
async function atomicJson(file,data){await fs.mkdir(path.dirname(file),{recursive:true});const temp=file+'.tmp';await fs.writeFile(temp,JSON.stringify(data,null,2));await fs.rename(temp,file);}
// RAD0 metadata is plain JSON. Read only its bounded header in the main process;
// importing Spark here pulls browser-only Three.js modules into Electron's archive.
async function radMeta(source){
 const prefix=async bytes=>{if(!remote(source)){const f=await fs.open(source,'r');try{const b=Buffer.alloc(bytes);const read=await f.read(b,0,bytes,0);if(read.bytesRead!==bytes)throw Error('Truncated RAD header.');return b;}finally{await f.close();}}
  const response=await fetch(source,{headers:{Range:'bytes=0-'+(bytes-1)},signal:AbortSignal.timeout(30000)});if(!response.ok||!response.body)throw Error('RAD metadata request failed: '+response.status);if(response.status===206&&!/^bytes 0-/.test(response.headers.get('content-range')||'')){await response.body.cancel();throw Error('Invalid RAD range response.');}const reader=response.body.getReader(),out=Buffer.alloc(bytes);let used=0;try{while(used<bytes){const {done,value}=await reader.read();if(done)break;const length=Math.min(value.length,bytes-used);out.set(value.subarray(0,length),used);used+=length;}}finally{await reader.cancel();}if(used!==bytes)throw Error('Truncated RAD header.');return out;};
 const first=await prefix(8);if(first.toString('ascii',0,4)!=='RAD0')throw Error('Expected a RAD0 file.');const size=first.readUInt32LE(4);if(size<2||size>1048568)throw Error('RAD metadata exceeds the supported 1 MiB header limit.');const header=await prefix(8+size);const meta=JSON.parse(header.toString('utf8',8));if(meta.version!==1||meta.type!=='gsplat'||!Number.isSafeInteger(meta.count)||meta.count<=0||!Array.isArray(meta.chunks)||!meta.chunks.length)throw Error('Invalid RAD metadata.');for(const chunk of meta.chunks){if(!Number.isSafeInteger(chunk.offset)||chunk.offset<0||!Number.isSafeInteger(chunk.bytes)||chunk.bytes<=0||(chunk.filename!==undefined&&typeof chunk.filename!=='string'))throw Error('Invalid RAD chunk metadata.');}const {assertPagedRad}=await import('../shared/rad.mjs');assertPagedRad(meta);return meta;
}
async function download(url,out){const r=await fetch(url,{signal:AbortSignal.timeout(600000)});if(!r.ok||!r.body)throw Error(`Download failed: ${r.status} ${url}`);await fs.mkdir(path.dirname(out),{recursive:true});await pipeline(Readable.fromWeb(r.body),require('node:fs').createWriteStream(out,{flags:'wx'}));}
async function copyFile(from,to){await fs.mkdir(path.dirname(to),{recursive:true});if(!await exists(to))await fs.copyFile(from,to);}
async function checkLocalPage(dir){for(const entry of await fs.readdir(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory()){await checkLocalPage(file);continue;}if(!/\.(html?|css|m?js)$/i.test(entry.name))continue;const text=await fs.readFile(file,'utf8');if(/(?:src|poster)\s*=\s*["']\s*(?:https?:)?\/\//i.test(text)||/<link\b[^>]*href\s*=\s*["']\s*(?:https?:)?\/\//i.test(text)||/(?:url\(|@import\s+|fetch\(|import\s*\(|from\s+)[\s"']*(?:https?:)?\/\//i.test(text))throw Error(`Portable page has an external resource: ${entry.name}. Bundle it locally or choose referenced export.`);}}
async function copyViewer(dist,output){
 const manifestPath=path.join(dist,'.vite','manifest.json');if(!await exists(manifestPath)){await fs.cp(path.join(dist,'assets'),path.join(output,'assets'),{recursive:true});return;}
 const manifest=JSON.parse(await fs.readFile(manifestPath,'utf8')),seen=new Set();
 const visit=async key=>{if(seen.has(key))return;seen.add(key);const entry=manifest[key];if(!entry)throw Error(`Missing build entry: ${key}`);for(const file of [entry.file,...entry.css||[],...entry.assets||[]])await copyFile(path.join(dist,file),path.join(output,file));for(const dep of [...entry.imports||[],...entry.dynamicImports||[]])await visit(dep);};await visit('index.html');
}
async function exportTour({project,hosting,projectRoot,sources,destination,dist,launcher,portable,omitSplats,progress=()=>{}}){
 const {validateProject,renderPage}=await import('../shared/project.mjs');const errors=validateProject(project);if(errors.length)throw Error(errors.join('\n'));if(!await exists(launcher))throw Error('Launcher is missing. Run npm run launcher before exporting.');
 const output=path.resolve(destination);if(contained(projectRoot,output))throw Error('Choose an export folder outside the working project.');await fs.mkdir(output,{recursive:true});if((await fs.readdir(output)).length)throw Error('Choose an empty export folder.');
 const p=structuredClone(project),h=structuredClone(hosting);await fs.writeFile(path.join(output,'EXPORT_INCOMPLETE.txt'),'Export is in progress. Do not distribute this folder.');
 let counter=0;const copied=new Map();
 const materialize=async(ref,kind)=>{if(!ref)return '';if(copied.has(ref))return copied.get(ref);if(remote(ref)&&!portable)return ref;const ext=path.extname(new URL(ref,'http://local/').pathname)||'.bin';const rel=remote(ref)?`imports/remote-${++counter}/asset${ext}`:ref;const target=path.resolve(output,rel);if(!contained(output,target))throw Error('Asset path escapes export.');progress(`Copying ${ref}`);
  const from=remote(ref)?ref:sourcePath(ref,projectRoot,sources);if(portable&&kind==='html'&&remote(from))throw Error('Portable export requires custom HTML pages and their assets to be imported locally.');if(remote(from))await download(from,target);else if(kind==='html'){await fs.mkdir(path.dirname(target),{recursive:true});await fs.cp(path.dirname(from),path.dirname(target),{recursive:true,force:false,errorOnExist:false,filter:async f=>!(await fs.lstat(f)).isSymbolicLink()});if(portable)await checkLocalPage(path.dirname(target));}else await copyFile(from,target);
  if(kind==='rad'){const meta=await radMeta(from);for(const chunk of meta.chunks||[]){if(!chunk.filename)continue;if(remote(chunk.filename)||chunk.filename.startsWith('/')||chunk.filename.includes('\\'))throw Error('RAD chunk must use a relative filename.');const to=path.resolve(path.dirname(target),chunk.filename);if(!contained(output,to))throw Error('RAD chunk path escapes export.');const src=remote(from)?new URL(chunk.filename,from).href:path.resolve(path.dirname(from),chunk.filename);if(remote(src)){if(!await exists(to))await download(src,to);}else await copyFile(src,to);}}
  copied.set(ref,rel);return rel;};
 try{
  await copyViewer(dist,output);await fs.copyFile(path.join(dist,'index.html'),path.join(output,'index.html'));await fs.cp(path.join(dist,'licenses'),path.join(output,'licenses'),{recursive:true});await fs.copyFile(launcher,path.join(output,'Launch Tour.exe'));
  p.cover=await materialize(p.cover,'media');for(const s of p.scenes){let ref=h.sceneUrls?.[s.id]||s.source;if(!remote(ref)&&/^https?:/i.test(h.assetBaseUrl||''))ref=new URL(ref,h.assetBaseUrl.endsWith('/')?h.assetBaseUrl:h.assetBaseUrl+'/').href;if(portable)s.source=await materialize(ref,'rad');else if(!omitSplats&&!remote(ref))await materialize(s.source,'rad');if(s.background?.type==='panorama')s.background.source=await materialize(s.background.source,'media');else if(s.background?.type==='splat'){let backgroundRef=s.background.source;if(!remote(backgroundRef)&&/^https?:/i.test(h.assetBaseUrl||''))backgroundRef=new URL(backgroundRef,h.assetBaseUrl.endsWith('/')?h.assetBaseUrl:h.assetBaseUrl+'/').href;if(portable)s.background.source=await materialize(backgroundRef,'rad');else if(!omitSplats&&!remote(backgroundRef))await materialize(s.background.source,'rad');}s.collider=await materialize(s.collider,'glb');s.thumbnail=await materialize(s.thumbnail,'media');if(s.audio)s.audio.source=await materialize(s.audio.source,'media');for(const v of s.viewpoints)if(v.audio)v.audio.source=await materialize(v.audio.source,'media');}
  if(portable){h.assetBaseUrl='./';h.sceneUrls={};}
  for(const pg of p.pages){pg.html=await materialize(pg.html,'html');for(const b of pg.blocks){if(b.type==='image')b.url=await materialize(b.url,'media');if(portable&&b.type==='embed'&&remote(b.url))throw Error(`Portable export cannot include external embed in “${pg.title}”. Remove it or use referenced-assets export.`);}if(!pg.html){await fs.mkdir(path.join(output,'pages'),{recursive:true});await fs.writeFile(path.join(output,'pages',pg.id+'.html'),renderPage(pg));}}
  const {defaultPerformance,presetFile}=await import('../shared/performance.mjs');const performance=p.performance||defaultPerformance();
  for(const preset of performance.presets)await atomicJson(path.join(output,'performance',preset.id+'.performance.json'),presetFile(preset));
  if(await exists(path.join(dist,'performance-spec')))await fs.cp(path.join(dist,'performance-spec'),path.join(output,'performance-spec'),{recursive:true});
  await atomicJson(path.join(output,'config','tour.json'),p);await atomicJson(path.join(output,'config','hosting.json'),h);await fs.writeFile(path.join(output,'README.txt'),`SPARK TOUR\n\nWindows: run Launch Tour.exe. A local browser and control tab open. Stop the server from its control tab or close the launcher console.\n\nLocal network / Quest: in the launcher control tab, choose Share on this network. Scan the QR or enter the HTTPS address on a device on the same network. A self-signed certificate warning appears on first use; verify the address against the launcher before continuing. Allow the launcher through Windows Firewall on private networks if needed. Stop sharing from the control tab.\n\nHosting: upload this folder to a static HTTPS host (the EXE is only for local Windows viewing). Preserve subdirectories. Serve .rad with HTTP Range / 206 responses. Configure CORS on a remote asset host.\n\nEdit config/hosting.json to change assetBaseUrl (relative or HTTPS, ending with /) or sceneUrls overrides. These settings affect splats, not the application.\n\nReopen this folder in Spark Tour Studio to edit the tour. Runtime code is bundled locally. External links/custom pages may still depend on online services.\n\nExport mode: ${portable?'portable':'referenced assets'}\n`);await fs.unlink(path.join(output,'EXPORT_INCOMPLETE.txt'));return output;
 }catch(e){await fs.writeFile(path.join(output,'EXPORT_INCOMPLETE.txt'),String(e));throw e;}
}
module.exports={exportTour,sourcePath,atomicJson,radMeta};
