const crypto=require('node:crypto');
class ImportQueue {
 constructor(worker,notify=()=>{}){this.worker=worker;this.notify=notify;this.jobs=[];this.paused=false;this.revision=0;this.active=null;}
 snapshot(){return {revision:this.revision,paused:this.paused,activeId:this.active?.id||null,jobs:this.jobs.map(({input,...job})=>structuredClone(job))};}
 emit(){this.revision++;this.notify(this.snapshot());}
 hasWork(){return !!this.active||this.jobs.some(j=>['queued','running'].includes(j.state)||(j.state==='completed'&&!j.acknowledged));}
 enqueue(inputs){for(const input of inputs)this.jobs.push({id:crypto.randomUUID(),name:input.name,kind:input.kind,options:structuredClone(input.options||{}),...(input.replaceSceneId?{replaceSceneId:input.replaceSceneId,expectedSource:input.expectedSource}:{}),input:structuredClone(input),state:'queued',progress:'Waiting',acknowledged:false});this.emit();void this.pump();return this.snapshot();}
 action(action,id){const job=this.jobs.find(j=>j.id===id);if(action==='pause')this.paused=true;else if(action==='resume')this.paused=false;else if(action==='cancel'){if(job?.state==='queued'){job.state='cancelled';job.progress='Cancelled';}else if(job?.state==='running'){job.state='cancelled';job.progress='Cancelling…';this.active?.cancel();}}else if(action==='retry'&&job&&['failed','cancelled'].includes(job.state)&&this.active?.id!==id){job.state='queued';job.progress='Waiting';delete job.error;}else if(action==='clear')this.jobs=this.jobs.filter(j=>['queued','running'].includes(j.state)||(j.state==='completed'&&!j.acknowledged)||this.active?.id===j.id);else if(action==='ack'&&job?.state==='completed'){job.acknowledged=true;if(job.replaceSceneId)job.progress='Scene updated';}else if(action==='discard'&&job?.state==='completed'){job.acknowledged=true;job.progress='Converted but not applied: the scene source changed or the scene was removed.';}else if(action==='reset'){if(this.hasWork())throw Error('Finish or cancel scene imports first.');this.jobs=[];this.paused=false;}this.emit();void this.pump();return this.snapshot();}
 cancelAll(){this.paused=true;for(const job of this.jobs)if(['queued','running'].includes(job.state)){job.state='cancelled';job.progress='Cancelled';}this.active?.cancel();this.emit();}
 async pump(){if(this.active||this.paused)return;const job=this.jobs.find(j=>j.state==='queued');if(!job)return;job.state='running';job.progress='Starting…';this.active={id:job.id,cancel:()=>{}};this.emit();try{const task=this.worker(job.input,text=>{if(job.state==='running'){job.progress=text;this.emit();}},job.id);this.active.cancel=task.cancel;const result=await task.promise;if(job.state!=='cancelled'){job.result=result;job.state='completed';job.progress='Imported';}}catch(e){if(job.state!=='cancelled'){job.state='failed';job.error=String(e.message||e);job.progress='Failed';}}finally{this.active=null;this.emit();void this.pump();}}
}
module.exports={ImportQueue};
