const {app,BrowserWindow,dialog,ipcMain,shell}=require('electron');const fs=require('node:fs/promises');const path=require('node:path');const crypto=require('node:crypto');const {startServer,contained}=require('./server.cjs');const {exportTour,sourcePath,atomicJson,radMeta}=require('./export.cjs');
if(process.env.SPARK_TEST==='1'&&process.env.SPARK_TEST_PROFILE)app.setPath('userData',path.resolve(process.env.SPARK_TEST_PROFILE));
const diagnosticRoot=path.join(app.getPath('userData'),'diagnostics');
const syncFs=require('node:fs');syncFs.mkdirSync(diagnosticRoot,{recursive:true});
app.setPath('crashDumps',path.join(diagnosticRoot,'crashes'));
require('electron').crashReporter.start({uploadToServer:false});
function diagnostic(event,details){try{syncFs.appendFileSync(path.join(diagnosticRoot,'events.jsonl'),JSON.stringify({time:new Date().toISOString(),version:app.getVersion(),event,...details})+'\n');}catch{}}
app.on('child-process-gone',(_event,details)=>diagnostic('child-process-gone',details));
process.on('uncaughtExceptionMonitor',error=>diagnostic('main-error',{message:error.message,stack:error.stack}));
let win,server,projectRoot='',sources={},base='';let busy=false;let conversion;let imports;let sourceWrites=Promise.resolve();
function persistSources(){const root=projectRoot,data=structuredClone(sources);sourceWrites=sourceWrites.catch(()=>{}).then(()=>atomicJson(path.join(root,".sources.json"),data));return sourceWrites;}
function requireIdleImports(){if(imports?.hasWork()||imports?.active)throw Error("Finish or cancel scene imports first.");}
const {convertPly}=require('./converter.cjs');
const {generateCollision}=require('./collision.cjs');
const dist=app.isPackaged?path.join(process.resourcesPath,'viewer'):path.join(__dirname,'..','dist');
async function read(file,fallback){try{return JSON.parse(await fs.readFile(file,'utf8'));}catch(e){if(e.code==='ENOENT')return fallback;throw e;}}
async function snapshot(project,hosting){return {project,hosting,base:base+'project/',path:projectRoot,recovery:await read(path.join(projectRoot,'autosave.json'),undefined)};}
async function folder(title){return (await dialog.showOpenDialog(win,{title,properties:['openDirectory','createDirectory']})).filePaths[0];}
function handle(name,fn){ipcMain.handle(name,async(event,...args)=>{if(event.sender!==win.webContents||event.senderFrame!==win.webContents.mainFrame)throw Error('Invalid editor caller.');if(busy&&!['project:autosave','conversion:cancel','imports:get','imports:action'].includes(name))throw Error('Another operation is already running.');return fn(...args);});}
app.whenReady().then(async()=>{
 const model=await import('../shared/project.mjs');
 imports=new (require('./import-queue.cjs').ImportQueue)((input,progress,id)=>{
  let cancelled=false,task;
  if(input.kind==='ply')task=convertPly({source:input.source,projectRoot:input.root,executable:app.isPackaged?path.join(process.resourcesPath,'converter','build-lod.exe'):path.join(__dirname,'..','converter','build-lod.exe'),...input.options,progress});
  else task={cancel:()=>{cancelled=true;},promise:(async()=>{progress('Checking RAD and companion chunks…');const meta=await radMeta(input.source);const dir=path.dirname(input.source);for(const chunk of meta.chunks){const file=chunk.filename?path.resolve(dir,chunk.filename):input.source;if(!contained(dir,file))throw Error('RAD chunk path escapes its source folder.');const stat=await fs.stat(file);if(stat.size<chunk.offset+chunk.bytes)throw Error('Incomplete RAD chunk: '+path.basename(file));}if(cancelled)throw Error('Cancelled');const prefix='imports/'+id;sources[prefix]={dir,kind:'rad'};await persistSources();return prefix+'/'+path.basename(input.source);})()};
  return {cancel:()=>{cancelled=true;task.cancel();},promise:task.promise.then(ref=>model.newScene(id,input.name,ref))};
 },state=>{if(win&&!win.isDestroyed())win.webContents.send('import-queue',state);});
 handle('imports:get',()=>imports.snapshot());
 handle('imports:action',(action,id)=>{if(!['pause','resume','cancel','retry','clear','ack'].includes(action))throw Error('Invalid import action.');if(busy&&['resume','retry'].includes(action))throw Error('Another operation is already running.');return imports.action(action,id);});
 handle('imports:choose',async(kind,options)=>{if(!projectRoot)throw Error('Create or open a project first.');if(!['ply','rad'].includes(kind))throw Error('Invalid scene type.');if(kind==='ply'&&(!options||!['quality','quick'].includes(options.method)||!Number.isInteger(options.maxSh)||options.maxSh<0||options.maxSh>3))throw Error('Invalid conversion settings.');const root=projectRoot;const result=await dialog.showOpenDialog(win,{title:'Queue '+kind.toUpperCase()+' scenes',properties:['openFile','multiSelections'],filters:[{name:kind.toUpperCase(),extensions:[kind]}]});if(root!==projectRoot)throw Error('Project changed while choosing files.');return imports.enqueue(result.filePaths.map(source=>({source,root,kind,name:path.basename(source,path.extname(source)),options:kind==='ply'?options:{}})));});
const running=await startServer({root:dist,resolve:name=>{if(name.startsWith('project/')){if(!projectRoot)return false;const rel=name.slice(8);for(const [prefix,info] of Object.entries(sources))if(rel.startsWith(prefix+'/'))return {root:info.dir,relative:rel.slice(prefix.length+1)};return {root:projectRoot,relative:rel};}}});server=running.server;base=running.url;
 win=new BrowserWindow({show:process.env.SPARK_TEST!=='1',width:1550,height:1000,minWidth:1050,minHeight:700,backgroundColor:'#101c24',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.webContents.on('render-process-gone',(_event,details)=>diagnostic('renderer-gone',details));win.webContents.setWindowOpenHandler(({url})=>{if(/^https?:/.test(url))void shell.openExternal(url);return {action:'deny'};});require('./close.cjs').attachClose({win,dialog,model,getRoot:()=>projectRoot,getSources:()=>sources,saveSources:persistSources,isBusy:()=>busy||imports.hasWork()||!!imports.active,cancelJob:()=>{conversion?.cancel();imports.cancelAll();}});win.webContents.on('will-navigate',(event,url)=>{if(!url.startsWith(base+'editor.html'))event.preventDefault();});
 handle('project:new',async()=>{requireIdleImports();const dir=await folder('Choose an empty project folder');if(!dir)return null;if((await fs.readdir(dir)).length)throw Error('Choose an empty folder for a new project.');imports.action("reset");projectRoot=dir;sources={};const p=model.blankProject(),h={assetBaseUrl:'./',sceneUrls:{}};await atomicJson(path.join(dir,'config','tour.json'),p);await atomicJson(path.join(dir,'config','hosting.json'),h);return snapshot(p,h);});
 handle('project:open',async()=>{requireIdleImports();const dir=await folder('Open a Spark Tour project or export');if(!dir)return null;const p=model.ProjectSchema.parse(await read(path.join(dir,'config','tour.json'),null));const h=model.HostingSchema.parse(await read(path.join(dir,'config','hosting.json'),{}));imports.action('reset');projectRoot=dir;sources=await read(path.join(dir,'.sources.json'),{});return snapshot(p,h);});
 handle('project:save',async(p,h,as)=>{p=model.ProjectSchema.parse(p);h=model.HostingSchema.parse(h);if(!projectRoot)throw Error('Create or open a project first.');if(as){requireIdleImports();const dir=await folder('Save project copy into an empty folder');if(!dir)return snapshot(p,h);if(contained(projectRoot,dir)||contained(dir,projectRoot))throw Error('Choose a separate folder.');if((await fs.readdir(dir)).length)throw Error('Choose an empty folder.');await fs.cp(projectRoot,dir,{recursive:true});projectRoot=dir;}await atomicJson(path.join(projectRoot,'config','tour.json'),p);await atomicJson(path.join(projectRoot,'config','hosting.json'),h);await persistSources();await fs.rm(path.join(projectRoot,'autosave.json'),{force:true});return snapshot(p,h);});
 handle('project:autosave',async p=>{if(projectRoot)await atomicJson(path.join(projectRoot,'autosave.json'),model.ProjectSchema.parse(p));});
 handle('conversion:cancel',async()=>{conversion?.cancel();});
 handle('asset:ply',async(options)=>{requireIdleImports();if(!projectRoot)throw Error('Create or open a project first.');if(!options||!['quality','quick'].includes(options.method)||!Number.isInteger(options.maxSh)||options.maxSh<0||options.maxSh>3)throw Error('Invalid conversion settings.');busy=true;try{const result=await dialog.showOpenDialog(win,{title:'Import Gaussian splat PLY',properties:['openFile'],filters:[{name:'Gaussian splat PLY',extensions:['ply']}]});const source=result.filePaths[0];if(!source)return null;conversion=convertPly({source,projectRoot,executable:app.isPackaged?path.join(process.resourcesPath,'converter','build-lod.exe'):path.join(__dirname,'..','converter','build-lod.exe'),method:options.method,maxSh:options.maxSh,progress:text=>{if(!win.isDestroyed())win.webContents.send('progress',text);}});return await conversion.promise;}finally{conversion=undefined;busy=false;}});
 handle('asset:collision',async options=>{requireIdleImports();if(!projectRoot)throw Error('Create or open a project first.');busy=true;try{const result=await dialog.showOpenDialog(win,{title:'Choose the matching source PLY for collision generation',properties:['openFile'],filters:[{name:'Gaussian splat PLY',extensions:['ply']}]});if(!result.filePaths[0])return null;conversion=generateCollision({source:result.filePaths[0],projectRoot,executable:path.join(app.isPackaged?process.resourcesPath:path.join(__dirname,'..'),'collision-tools','node.exe'),cli:path.join(app.isPackaged?process.resourcesPath:path.join(__dirname,'..'),'collision-tools','node_modules','@playcanvas','splat-transform','bin','cli.mjs'),voxelSize:options?.voxelSize,scale:options?.scale,maxGaussians:options?.maxGaussians,progress:text=>{if(!win.isDestroyed())win.webContents.send('progress',text);}});return await conversion.promise;}finally{conversion=undefined;busy=false;}});
 const performance=await import('../shared/performance.mjs');
 handle('performance:import',async()=>{const result=await dialog.showOpenDialog(win,{title:'Import performance preset',properties:['openFile'],filters:[{name:'Performance preset',extensions:['json']}]});if(!result.filePaths[0])return null;const file=result.filePaths[0];if((await fs.stat(file)).size>65536)throw Error('Preset file is too large.');return performance.PerformancePresetSchema.parse(JSON.parse(await fs.readFile(file,'utf8')));});
 handle('performance:export',async value=>{const preset=performance.PerformancePresetSchema.parse(value);const result=await dialog.showSaveDialog(win,{title:'Save performance preset',defaultPath:preset.name.replace(/[^a-zA-Z0-9 _-]/g,'')+'.performance.json',filters:[{name:'Performance preset',extensions:['json']}]});if(result.canceled||!result.filePath)return null;await atomicJson(result.filePath,preset);return result.filePath;});
 handle('asset:image-file',async file=>{if(!projectRoot)throw Error('Create or open a project first.');if(typeof file!=='string'||!path.isAbsolute(file)||!['.png','.jpg','.jpeg','.webp','.svg','.gif','.avif'].includes(path.extname(file).toLowerCase()))throw Error('Choose a PNG, JPEG, WebP, SVG, GIF or AVIF image file.');const stat=await fs.stat(file);if(!stat.isFile()||stat.size>64*1024*1024)throw Error('Choose an image smaller than 64 MB.');const ref='media/'+crypto.randomUUID()+path.extname(file).toLowerCase();await fs.mkdir(path.join(projectRoot,'media'),{recursive:true});await fs.copyFile(file,path.join(projectRoot,ref));return ref;});
 handle('asset:import',async kind=>{if(!projectRoot)throw Error('Create or open a project first.');const extensions=kind==='rad'?['rad']:kind==='collider'?['glb']:kind==='html'?['html','htm']:kind==='audio'?['mp3','wav','ogg','m4a','aac','flac','webm']:['png','jpg','jpeg','webp','svg','gif','avif'];const result=await dialog.showOpenDialog(win,{title:kind==='html'?'Select HTML page (its containing folder is included on export)':'Choose '+kind,properties:['openFile'],filters:[{name:kind,extensions}]});const file=result.filePaths[0];if(!file)return null;const prefix='imports/'+crypto.randomUUID();sources[prefix]={dir:path.dirname(file),kind};await persistSources();return prefix+'/'+path.basename(file);});
 handle('asset:validate',async(p,h={})=>{const errors=model.validateProject(p);const parsed=model.ProjectSchema.safeParse(p);if(!parsed.success)return errors;p=parsed.data;for(const ref of model.allReferences(p,model.HostingSchema.parse(h))){if(/^https?:/i.test(ref))continue;try{await fs.access(sourcePath(ref,projectRoot,sources));}catch{errors.push(`Missing asset: ${ref}`);}}return errors;});
 handle('tour:export',async(p,h,portable,omitSplats)=>{requireIdleImports();const destination=await folder('Export into an empty folder');if(!destination)return null;busy=true;try{return await exportTour({project:p,hosting:h,portable,omitSplats,projectRoot,sources,destination,dist,launcher:app.isPackaged?path.join(process.resourcesPath,'Launch Tour.exe'):path.join(__dirname,'..','launcher','Launch Tour.exe'),progress:s=>win.webContents.send('progress',s)});}finally{busy=false;}});
 await win.loadURL(base+'editor.html');
});
app.on('before-quit',()=>{conversion?.cancel();imports?.cancelAll();});
app.on('window-all-closed',()=>{conversion?.cancel();imports?.cancelAll();server?.close();app.quit();});
