const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.wasm':'application/wasm','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.gif':'image/gif','.avif':'image/avif','.pdf':'application/pdf','.svg':'image/svg+xml','.mp4':'video/mp4','.mp3':'audio/mpeg','.m4a':'audio/mp4','.wav':'audio/wav','.ogg':'audio/ogg','.aac':'audio/aac','.flac':'audio/flac','.webm':'video/webm','.woff2':'font/woff2'};
function contained(root,file){const rel=path.relative(root,file);return rel===''||(!rel.startsWith('..'+path.sep)&&rel!=='..'&&!path.isAbsolute(rel));}
function rangeFor(header,size){if(!header)return null;const match=/^bytes=(\d*)-(\d*)$/.exec(header);if(!match||(!match[1]&&!match[2]))throw Error('range');let start=match[1]?Number(match[1]):Math.max(0,size-Number(match[2]));let end=match[1]?(match[2]?Math.min(Number(match[2]),size-1):size-1):size-1;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start>end||start>=size||start<0)throw Error('range');return {start,end};}
async function fileResponse(req,res,root,relative){
 try{if(relative.includes('\0')||relative.includes('\\'))throw Error('path');const file=path.resolve(root,relative||'index.html');if(!contained(path.resolve(root),file)){res.writeHead(403).end();return;}const real=await fs.promises.realpath(file);if(!contained(await fs.promises.realpath(root),real)){res.writeHead(403).end();return;}const stat=await fs.promises.stat(real);if(!stat.isFile()){res.writeHead(404).end();return;}let range;try{range=rangeFor(req.headers.range,stat.size);}catch{res.writeHead(416,{'Content-Range':`bytes */${stat.size}`}).end();return;}const headers={'Content-Type':types[path.extname(real).toLowerCase()]||'application/octet-stream','Accept-Ranges':'bytes','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'};if(range){headers['Content-Range']=`bytes ${range.start}-${range.end}/${stat.size}`;headers['Content-Length']=range.end-range.start+1;}else headers['Content-Length']=stat.size;res.writeHead(range?206:200,headers);if(req.method==='HEAD'){res.end();return;}const stream=fs.createReadStream(real,range||{});stream.on('error',()=>res.destroy());res.on('close',()=>stream.destroy());stream.pipe(res);
 }catch{if(!res.headersSent)res.writeHead(404).end('File not found');else res.destroy();}
}
function startServer({root,resolve,control,shutdown=false,onShutdown=()=>{}}){return new Promise((ok,fail)=>{const token=crypto.randomBytes(24).toString('hex');const server=http.createServer(async(req,res)=>{
 const local=`127.0.0.1:${server.address().port}`;if(req.headers.host!==local&&req.headers.host!==`localhost:${server.address().port}`){res.writeHead(403).end();return;}
 let name;try{name=decodeURIComponent(new URL(req.url,`http://${local}`).pathname).slice(1);}catch{res.writeHead(400).end();return;}
 if(control){try{if(await control({name,req,res,token}))return;}catch{res.writeHead(500).end('Launcher control failed.');return;}}
 if(shutdown&&name==='__launcher'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}).end(`<html><title>Tour launcher</title><body style="font:20px system-ui;padding:50px;background:#11232b;color:white"><h1>Tour is running</h1><p>Keep this launcher running while viewing.</p><p><a style="color:#a8f5dc" target="_blank" href="/">Open tour</a></p><form method="post" action="/__shutdown"><input type="hidden" name="token" value="${token}"><button>Stop tour server</button></form></body></html>`);return;}
 if(shutdown&&name==='__shutdown'&&req.method==='POST'){let body='';req.on('data',c=>{body+=c;if(body.length>512)req.destroy();});req.on('end',()=>{if(body!==`token=${token}`){res.writeHead(403).end();return;}res.end('Tour stopped. You can close this tab.');server.close();setTimeout(onShutdown,100);});return;}
 if(!['GET','HEAD'].includes(req.method)){res.writeHead(405).end();return;}
 const target=resolve?.(name);if(target===false){res.writeHead(404).end();return;}await fileResponse(req,res,target?.root||root,target?.relative??name);
 });server.on('error',fail);server.listen(0,'127.0.0.1',()=>ok({server,url:`http://127.0.0.1:${server.address().port}/`}));});}
module.exports={contained,rangeFor,fileResponse,startServer};
